import { Volmet } from "../../volmet/entities/volmet.entity";

export const VOLMET_DATA: Partial<Volmet>[] = [
  {
    icao: "LIRF",
    iata: "FCO",
    name: "Roma Fiumicino",
    city: "Roma Fiumicino",
    country: "IT",
    latitude: 41.8003,
    longitude: 12.2389,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "126.125",
    isActive: true,
  },
  {
    icao: "LIRA",
    iata: "CIA",
    name: "Roma Ciampino",
    city: "Roma Ciampino",
    country: "IT",
    latitude: 41.7994,
    longitude: 12.5949,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "122.425",
    isActive: true,
  },
  {
    icao: "LIMC",
    iata: "MXP",
    name: "Milano Malpensa",
    city: "Milano Malpensa",
    country: "IT",
    latitude: 45.6306,
    longitude: 8.7281,
    frequencies: ["126.600"],
    region: "Italy",
    volmetName: "Milano VOLMET",
    atis: "120.025",
    isActive: true,
  },
  {
    icao: "LIME",
    iata: "BGY",
    name: "Bergamo Orio al Serio",
    city: "Bergamo Orio al Serio",
    country: "IT",
    latitude: 45.6739,
    longitude: 9.7042,
    frequencies: ["126.600"],
    region: "Italy",
    volmetName: "Milano VOLMET",
    atis: "114.95",
    isActive: true,
  },
  {
    icao: "LIBD",
    iata: "BRI",
    name: "Bari",
    city: "Bari",
    country: "IT",
    latitude: 41.1389,
    longitude: 16.7606,
    frequencies: ["5450"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "124.050",
    isActive: true,
  },
  {
    icao: "LIBE",
    iata: "BDS",
    name: "Brindisi",
    city: "Brindisi",
    country: "IT",
    latitude: 40.6576,
    longitude: 17.947,
    frequencies: ["127.6"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "123.900",
    isActive: true,
  },
  {
    icao: "LIEE",
    iata: "CAG",
    name: "Cagliari",
    city: "Cagliari",
    country: "IT",
    latitude: 39.2515,
    longitude: 9.0543,
    frequencies: ["127.750"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "127.055",
    isActive: true,
  },
  {
    icao: "LICC",
    iata: "CTA",
    name: "Catania",
    city: "Catania",
    country: "IT",
    latitude: 37.4668,
    longitude: 15.0664,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "127.675",
    isActive: true,
  },
  {
    icao: "LICJ",
    iata: "PMO",
    name: "Palermo",
    city: "Palermo",
    country: "IT",
    latitude: 38.176,
    longitude: 13.091,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "123.875",
    isActive: true,
  },
  {
    icao: "LIRN",
    iata: "NAP",
    name: "Napoli",
    city: "Napoli",
    country: "IT",
    latitude: 40.886,
    longitude: 14.2908,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "135.975",
    isActive: true,
  },
  {
    icao: "LIPZ",
    iata: "VCE",
    name: "Venezia Marco Polo",
    city: "Venezia Marco Polo",
    country: "IT",
    latitude: 45.5053,
    longitude: 12.3519,
    frequencies: ["126.600"],
    region: "Italy",
    volmetName: "Milano VOLMET",
    atis: "131.100",
    isActive: true,
  },
  {
    icao: "LIPH",
    iata: "TSF",
    name: "Venezia Treviso",
    city: "Venezia Treviso",
    country: "IT",
    latitude: 45.6484,
    longitude: 12.1944,
    frequencies: ["126.625"],
    region: "Italy",
    volmetName: "Milano VOLMET",
    atis: "128.100",
    isActive: true,
  },
  {
    icao: "LIPE",
    iata: "BLQ",
    name: "Bologna",
    city: "Bologna",
    country: "IT",
    latitude: 44.5354,
    longitude: 11.2887,
    frequencies: ["128.400"],
    region: "Italy",
    volmetName: "Milano VOLMET",
    atis: "134.875",
    isActive: true,
  },
  {
    icao: "LICP",
    iata: "TPS",
    name: "Trapani",
    city: "Trapani",
    country: "IT",
    latitude: 37.9114,
    longitude: 12.4879,
    frequencies: ["127.750"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "121.700",
    isActive: true,
  },
  {
    icao: "LIPQ",
    iata: "TRS",
    name: "Trieste",
    city: "Trieste",
    country: "IT",
    latitude: 45.8275,
    longitude: 13.4722,
    frequencies: ["126.625"],
    region: "Italy",
    volmetName: "Milano VOLMET",
    atis: "124.100",
    isActive: true,
  },
  {
    icao: "LIMF",
    iata: "TRN",
    name: "Torino",
    city: "Torino",
    country: "IT",
    latitude: 45.2008,
    longitude: 7.6497,
    frequencies: ["128.400"],
    region: "Italy",
    volmetName: "Milano VOLMET",
    atis: "127.850",
    isActive: true,
  },
  {
    icao: "LIEA",
    iata: "AHO",
    name: "Alghero",
    city: "Alghero",
    country: "IT",
    latitude: 40.6321,
    longitude: 8.2908,
    frequencies: ["127.750"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "125.025",
    isActive: true,
  },
  {
    icao: "LIPY",
    iata: "AOI",
    name: "Ancona",
    city: "Ancona",
    country: "IT",
    latitude: 43.6163,
    longitude: 13.3623,
    frequencies: ["127.750"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "119.350",
    isActive: true,
  },
  {
    icao: "LICA",
    iata: "SUF",
    name: "Lamezia Terme",
    city: "Lamezia Terme",
    country: "IT",
    latitude: 38.9054,
    longitude: 16.2423,
    frequencies: ["127.750"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "119.930",
    isActive: true,
  },
  {
    icao: "LIRP",
    iata: "PSA",
    name: "Pisa",
    city: "Pisa",
    country: "IT",
    latitude: 43.6839,
    longitude: 10.3927,
    frequencies: ["128.400"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "130.065",
    isActive: true,
  },
  {
    icao: "LIPK",
    iata: "FRL",
    name: "Forli",
    city: "Forli",
    country: "IT",
    latitude: 44.1948,
    longitude: 12.0701,
    frequencies: ["126.625"],
    region: "Italy",
    volmetName: "Milano VOLMET",
    atis: "119.825",
    isActive: true,
  },
  {
    icao: "LIBR",
    iata: "CRV",
    name: "Crotone",
    city: "Crotone",
    country: "IT",
    latitude: 38.9972,
    longitude: 17.0802,
    frequencies: ["127.600"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "119.215",
    isActive: true,
  },
  {
    icao: "LIBV",
    iata: "REG",
    name: "Reggio Calabria",
    city: "Reggio Calabria",
    country: "IT",
    latitude: 38.0712,
    longitude: 15.6516,
    frequencies: ["127.750"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "119.200",
    isActive: true,
  },
  {
    icao: "LIMP",
    iata: "PMF",
    name: "Parma",
    city: "Parma",
    country: "IT",
    latitude: 44.8245,
    longitude: 10.2964,
    frequencies: ["126.625"],
    region: "Italy",
    volmetName: "Milano VOLMET",
    atis: "128.525",
    isActive: true,
  },
  {
    icao: "LIRZ",
    iata: "PEG",
    name: "Perugia",
    city: "Perugia",
    country: "IT",
    latitude: 43.0959,
    longitude: 12.5132,
    frequencies: ["127.750"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "119.850",
    isActive: true,
  },
  {
    icao: "LIBP",
    iata: "PSR",
    name: "Pescara",
    city: "Pescara",
    country: "IT",
    latitude: 42.4317,
    longitude: 14.1811,
    frequencies: ["127.750"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "120.125",
    isActive: true,
  },
  {
    icao: "LIPI",
    iata: "RMI",
    name: "Rimini",
    city: "Rimini",
    country: "IT",
    latitude: 44.0204,
    longitude: 12.6117,
    frequencies: ["126.625"],
    region: "Italy",
    volmetName: "Milano VOLMET",
    atis: "123.800",
    isActive: true,
  },
  {
    icao: "LIED",
    iata: "QSR",
    name: "Salerno",
    city: "Salerno",
    country: "IT",
    latitude: 40.6204,
    longitude: 14.9113,
    frequencies: ["127.750"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "119.650",
    isActive: true,
  },
  {
    icao: "LIMJ",
    iata: "GOA",
    name: "Genova",
    city: "Genova",
    country: "IT",
    latitude: 44.4133,
    longitude: 8.8375,
    frequencies: ["126.600"],
    region: "Italy",
    volmetName: "Milano VOLMET",
    atis: "122.825",
    isActive: true,
  },
  {
    icao: "LIPX",
    iata: "VRN",
    name: "Verona",
    city: "Verona",
    country: "IT",
    latitude: 45.3957,
    longitude: 10.8885,
    frequencies: ["126.625"],
    region: "Italy",
    volmetName: "Milano VOLMET",
    atis: "126.350",
    isActive: true,
  },
  {
    icao: "LIPC",
    iata: "CUF",
    name: "Cuneo",
    city: "Cuneo",
    country: "IT",
    latitude: 44.547,
    longitude: 7.6232,
    frequencies: ["126.625"],
    region: "Italy",
    volmetName: "Milano VOLMET",
    atis: "120.100",
    isActive: true,
  },
  {
    icao: "LIEO",
    iata: "OLB",
    name: "Olbia",
    city: "Olbia",
    country: "IT",
    latitude: 40.8987,
    longitude: 9.5176,
    frequencies: ["127.750"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "127.575",
    isActive: true,
  },
  {
    icao: "EGSS",
    iata: "STN",
    name: "London Stansted",
    city: "London Stansted",
    country: "GB",
    latitude: 51.885,
    longitude: 0.235,
    frequencies: ["135.375"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "127.180",
    isActive: true,
  },
  {
    icao: "EGGW",
    iata: "LTN",
    name: "London Luton",
    city: "London Luton",
    country: "GB",
    latitude: 51.8747,
    longitude: -0.3683,
    frequencies: ["128.600"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "120.580",
    isActive: true,
  },
  {
    icao: "EGKK",
    iata: "LGW",
    name: "London Gatwick",
    city: "London Gatwick",
    country: "GB",
    latitude: 51.1481,
    longitude: -0.1903,
    frequencies: ["135.375"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "136.525",
    isActive: true,
  },
  {
    icao: "EGCC",
    iata: "MAN",
    name: "Manchester",
    city: "Manchester",
    country: "GB",
    latitude: 53.3537,
    longitude: -2.275,
    frequencies: ["135.375"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "128.180",
    isActive: true,
  },
  {
    icao: "EGBB",
    iata: "BHX",
    name: "Birmingham",
    city: "Birmingham",
    country: "GB",
    latitude: 52.4539,
    longitude: -1.748,
    frequencies: ["128.600"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "136.030",
    isActive: true,
  },
  {
    icao: "EGPH",
    iata: "EDI",
    name: "Edinburgh",
    city: "Edinburgh",
    country: "GB",
    latitude: 55.95,
    longitude: -3.3725,
    frequencies: ["125.725"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "131.355",
    isActive: true,
  },
  {
    icao: "EGPK",
    iata: "PIK",
    name: "Glasgow Prestwick",
    city: "Glasgow Prestwick",
    country: "GB",
    latitude: 55.5094,
    longitude: -4.5867,
    frequencies: ["125.725"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "121.130",
    isActive: true,
  },
  {
    icao: "EGGD",
    iata: "BRS",
    name: "Bristol",
    city: "Bristol",
    country: "GB",
    latitude: 51.3827,
    longitude: -2.7191,
    frequencies: ["128.600"],
    region: "United Kingdom",
    volmetName: "London VOLMET South",
    atis: "126.030",
    isActive: true,
  },
  {
    icao: "EGNX",
    iata: "EMA",
    name: "East Midlands",
    city: "East Midlands",
    country: "GB",
    latitude: 52.8311,
    longitude: -1.3281,
    frequencies: ["126.600"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "122.680",
    isActive: true,
  },
  {
    icao: "EGNT",
    iata: "NCL",
    name: "Newcastle",
    city: "Newcastle",
    country: "GB",
    latitude: 55.0375,
    longitude: -1.6917,
    frequencies: ["126.600"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "118.380",
    isActive: true,
  },
  {
    icao: "EGHH",
    iata: "BOH",
    name: "Bournemouth",
    city: "Bournemouth",
    country: "GB",
    latitude: 50.78,
    longitude: -1.8425,
    frequencies: ["128.600"],
    region: "United Kingdom",
    volmetName: "London VOLMET South",
    atis: "133.725",
    isActive: true,
  },
  {
    icao: "EGNM",
    iata: "LBA",
    name: "Leeds Bradford",
    city: "Leeds Bradford",
    country: "GB",
    latitude: 53.8659,
    longitude: -1.6606,
    frequencies: ["126.600"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "118.030",
    isActive: true,
  },
  {
    icao: "EGGP",
    iata: "LPL",
    name: "Liverpool",
    city: "Liverpool",
    country: "GB",
    latitude: 53.3336,
    longitude: -2.8497,
    frequencies: ["126.600"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "124.330",
    isActive: true,
  },
  {
    icao: "EGAA",
    iata: "BFS",
    name: "Belfast International",
    city: "Belfast International",
    country: "GB",
    latitude: 54.6575,
    longitude: -6.2158,
    frequencies: ["125.725"],
    region: "United Kingdom",
    volmetName: "Shannon VOLMET",
    atis: "126.130",
    isActive: true,
  },
  {
    icao: "EGAE",
    iata: "LDY",
    name: "Derry",
    city: "Derry",
    country: "GB",
    latitude: 55.0428,
    longitude: -7.1611,
    frequencies: ["127.500"],
    region: "United Kingdom",
    volmetName: "Shannon VOLMET",
    atis: "119.000",
    isActive: true,
  },
  {
    icao: "EGHI",
    iata: "SOU",
    name: "Southampton",
    city: "Southampton",
    country: "GB",
    latitude: 50.9503,
    longitude: -1.3569,
    frequencies: ["128.600"],
    region: "United Kingdom",
    volmetName: "London VOLMET South",
    atis: "113.350",
    isActive: true,
  },
  {
    icao: "EGTE",
    iata: "EXT",
    name: "Exeter",
    city: "Exeter",
    country: "GB",
    latitude: 50.7344,
    longitude: -3.4139,
    frequencies: ["128.600"],
    region: "United Kingdom",
    volmetName: "London VOLMET South",
    atis: "119.325",
    isActive: true,
  },
  {
    icao: "EGPD",
    iata: "ABZ",
    name: "Aberdeen",
    city: "Aberdeen",
    country: "GB",
    latitude: 57.2019,
    longitude: -2.1978,
    frequencies: ["125.725"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "121.855",
    isActive: true,
  },
  {
    icao: "EGJA",
    iata: "NQY",
    name: "Newquay",
    city: "Newquay",
    country: "GB",
    latitude: 50.4406,
    longitude: -4.9951,
    frequencies: ["128.600"],
    region: "United Kingdom",
    volmetName: "London VOLMET South",
    atis: "119.300",
    isActive: true,
  },
  {
    icao: "EGCF",
    iata: "CWL",
    name: "Cardiff",
    city: "Cardiff",
    country: "GB",
    latitude: 51.3967,
    longitude: -3.3433,
    frequencies: ["128.600"],
    region: "United Kingdom",
    volmetName: "London VOLMET South",
    atis: "119.475",
    isActive: true,
  },
  {
    icao: "EGNV",
    iata: "MME",
    name: "Teesside",
    city: "Teesside",
    country: "GB",
    latitude: 54.5092,
    longitude: -1.4294,
    frequencies: ["135.375"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "128.850",
    isActive: true,
  },
  {
    icao: "EGSH",
    iata: "NWI",
    name: "Norwich",
    city: "Norwich",
    country: "GB",
    latitude: 52.6758,
    longitude: 1.2828,
    frequencies: ["135.375"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "128.625",
    isActive: true,
  },
  {
    icao: "EIDW",
    iata: "DUB",
    name: "Dublino",
    city: "Dublino",
    country: "IR",
    latitude: 53.4213,
    longitude: -6.2701,
    frequencies: ["127.005"],
    region: "Irlanda",
    volmetName: "Shannon VOLMET",
    atis: "124.530",
    isActive: true,
  },
  {
    icao: "EINN",
    iata: "SNN",
    name: "Shannon",
    city: "Shannon",
    country: "IR",
    latitude: 52.702,
    longitude: -8.9248,
    frequencies: ["127.005"],
    region: "Irlanda",
    volmetName: "Shannon VOLMET",
    atis: "130.955",
    isActive: true,
  },
  {
    icao: "EICK",
    iata: "ORK",
    name: "Cork",
    city: "Cork",
    country: "IR",
    latitude: 51.8413,
    longitude: -8.4911,
    frequencies: ["127.005"],
    region: "Irlanda",
    volmetName: "Shannon VOLMET",
    atis: "120.925",
    isActive: true,
  },
  {
    icao: "EIKY",
    iata: "KIR",
    name: "Kerry",
    city: "Kerry",
    country: "IR",
    latitude: 52.1809,
    longitude: -9.5238,
    frequencies: ["127.500"],
    region: "Irlanda",
    volmetName: "Shannon VOLMET",
    atis: "118.025",
    isActive: true,
  },
  {
    icao: "EIKN",
    iata: "NOC",
    name: "Knock",
    city: "Knock",
    country: "IR",
    latitude: 53.9103,
    longitude: -8.8185,
    frequencies: ["127.500"],
    region: "Irlanda",
    volmetName: "Shannon VOLMET",
    atis: "118.525",
    isActive: true,
  },
  {
    icao: "LEMD",
    iata: "MAD",
    name: "Madrid",
    city: "Madrid",
    country: "SP",
    latitude: 40.4936,
    longitude: -3.5668,
    frequencies: ["126.205"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "118.255",
    isActive: true,
  },
  {
    icao: "LEBL",
    iata: "BCN",
    name: "Barcellona",
    city: "Barcellona",
    country: "SP",
    latitude: 41.2971,
    longitude: 2.0785,
    frequencies: ["127.605"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "118.655",
    isActive: true,
  },
  {
    icao: "LEPA",
    iata: "PMI",
    name: "Palma de Mallorca",
    city: "Palma de Mallorca",
    country: "SP",
    latitude: 39.5517,
    longitude: 2.7388,
    frequencies: ["127.605"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "119.255",
    isActive: true,
  },
  {
    icao: "LEAL",
    iata: "ALC",
    name: "Alicante",
    city: "Alicante",
    country: "SP",
    latitude: 38.2822,
    longitude: -0.5582,
    frequencies: ["126.205"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "120.080",
    isActive: true,
  },
  {
    icao: "LEMG",
    iata: "AGP",
    name: "Malaga",
    city: "Malaga",
    country: "SP",
    latitude: 36.6749,
    longitude: -4.4991,
    frequencies: ["126.205"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "120.380",
    isActive: true,
  },
  {
    icao: "LEZL",
    iata: "SVQ",
    name: "Siviglia",
    city: "Siviglia",
    country: "SP",
    latitude: 37.418,
    longitude: -5.8931,
    frequencies: ["128.380"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "118.175",
    isActive: true,
  },
  {
    icao: "LEVC",
    iata: "VLC",
    name: "Valencia",
    city: "Valencia",
    country: "SP",
    latitude: 39.4893,
    longitude: -0.4816,
    frequencies: ["126.005"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "118.300",
    isActive: true,
  },
  {
    icao: "LEST",
    iata: "SCQ",
    name: "Santiago de Compostela",
    city: "Santiago de Compostela",
    country: "SP",
    latitude: 42.8963,
    longitude: -8.4151,
    frequencies: ["126.605"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "120.600",
    isActive: true,
  },
  {
    icao: "LEIB",
    iata: "IBZ",
    name: "Ibiza",
    city: "Ibiza",
    country: "SP",
    latitude: 38.8729,
    longitude: 1.3731,
    frequencies: ["127.605"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "119.800",
    isActive: true,
  },
  {
    icao: "GCFV",
    iata: "FUE",
    name: "Fuerteventura",
    city: "Fuerteventura",
    country: "SP",
    latitude: 28.4527,
    longitude: -13.8638,
    frequencies: ["126.200"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "118.650",
    isActive: true,
  },
  {
    icao: "GCRR",
    iata: "ACE",
    name: "Lanzarote",
    city: "Lanzarote",
    country: "SP",
    latitude: 28.9455,
    longitude: -13.6052,
    frequencies: ["126.200"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "118.625",
    isActive: true,
  },
  {
    icao: "GCTS",
    iata: "TFS",
    name: "Tenerife Sur",
    city: "Tenerife Sur",
    country: "SP",
    latitude: 28.0445,
    longitude: -16.5725,
    frequencies: ["126.200"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "130.075",
    isActive: true,
  },
  {
    icao: "GCLP",
    iata: "LPA",
    name: "Gran Canaria",
    city: "Gran Canaria",
    country: "SP",
    latitude: 27.9319,
    longitude: -15.3866,
    frequencies: ["126.200"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "118.600",
    isActive: true,
  },
  {
    icao: "GCXO",
    iata: "TFN",
    name: "Tenerife Nord",
    city: "Tenerife Nord",
    country: "SP",
    latitude: 28.4827,
    longitude: -16.3414,
    frequencies: ["126.200"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "118.125",
    isActive: true,
  },
  {
    icao: "LERS",
    iata: "REU",
    name: "Reus",
    city: "Reus",
    country: "SP",
    latitude: 41.1474,
    longitude: 1.1672,
    frequencies: ["127.625"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "120.400",
    isActive: true,
  },
  {
    icao: "LEAM",
    iata: "LEI",
    name: "Almeria",
    city: "Almeria",
    country: "SP",
    latitude: 36.8439,
    longitude: -2.3701,
    frequencies: ["126.200"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "118.325",
    isActive: true,
  },
  {
    icao: "LEMH",
    iata: "MAH",
    name: "Menorca",
    city: "Menorca",
    country: "SP",
    latitude: 39.8626,
    longitude: 4.2186,
    frequencies: ["127.605"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "129.150",
    isActive: true,
  },
  {
    icao: "LEAS",
    iata: "OVD",
    name: "Asturias",
    city: "Asturias",
    country: "SP",
    latitude: 43.5636,
    longitude: -6.0346,
    frequencies: ["126.200"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "124.050",
    isActive: true,
  },
  {
    icao: "LEVT",
    iata: "VIT",
    name: "Vitoria",
    city: "Vitoria",
    country: "SP",
    latitude: 42.8828,
    longitude: -2.7245,
    frequencies: ["126.200"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "118.175",
    isActive: true,
  },
  {
    icao: "LEZG",
    iata: "ZAZ",
    name: "Zaragoza",
    city: "Zaragoza",
    country: "SP",
    latitude: 41.6662,
    longitude: -1.0415,
    frequencies: ["126.200"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "121.300",
    isActive: true,
  },
  {
    icao: "LEXJ",
    iata: "SDR",
    name: "Santander",
    city: "Santander",
    country: "SP",
    latitude: 43.4272,
    longitude: -3.82,
    frequencies: ["126.200"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "119.375",
    isActive: true,
  },
  {
    icao: "LEGE",
    iata: "GRO",
    name: "Girona",
    city: "Girona",
    country: "SP",
    latitude: 41.901,
    longitude: 2.7605,
    frequencies: ["127.605"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "128.750",
    isActive: true,
  },
  {
    icao: "LELC",
    iata: "MJV",
    name: "Murcia",
    city: "Murcia",
    country: "SP",
    latitude: 37.775,
    longitude: -0.8124,
    frequencies: ["126.200"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "120.700",
    isActive: true,
  },
  {
    icao: "LERL",
    iata: "CDT",
    name: "Castellon",
    city: "Castellon",
    country: "SP",
    latitude: 40.0214,
    longitude: 0.0731,
    frequencies: ["126.200"],
    region: "Spagna",
    volmetName: "Madrid VOLMET",
    atis: "119.350",
    isActive: true,
  },
  {
    icao: "LPPT",
    iata: "LIS",
    name: "Lisbona",
    city: "Lisbona",
    country: "PO",
    latitude: 38.7742,
    longitude: -9.1342,
    frequencies: ["126.405"],
    region: "Portogallo",
    volmetName: "Lisbon VOLMET",
    atis: "124.155",
    isActive: true,
  },
  {
    icao: "LPPR",
    iata: "OPO",
    name: "Porto",
    city: "Porto",
    country: "PO",
    latitude: 41.2481,
    longitude: -8.6814,
    frequencies: ["126.605"],
    region: "Portogallo",
    volmetName: "Lisbon VOLMET",
    atis: "124.305",
    isActive: true,
  },
  {
    icao: "LPFR",
    iata: "FAO",
    name: "Faro",
    city: "Faro",
    country: "PO",
    latitude: 37.0144,
    longitude: -7.9659,
    frequencies: ["126.405"],
    region: "Portogallo",
    volmetName: "Lisbon VOLMET",
    atis: "124.205",
    isActive: true,
  },
  {
    icao: "LPMA",
    iata: "FNC",
    name: "Madeira Funchal",
    city: "Madeira Funchal",
    country: "PO",
    latitude: 32.6979,
    longitude: -16.7745,
    frequencies: ["126.405"],
    region: "Portogallo",
    volmetName: "Lisbon VOLMET",
    atis: "130.355",
    isActive: true,
  },
  {
    icao: "LPLA",
    iata: "TER",
    name: "Azzorre Lajes",
    city: "Azzorre Lajes",
    country: "PO",
    latitude: 38.7618,
    longitude: -27.0908,
    frequencies: ["127.125", "13.264"],
    region: "Portogallo",
    volmetName: "Lisbon VOLMET / Shannon HF",
    atis: "119.200",
    isActive: true,
  },
  {
    icao: "LPPD",
    iata: "PDL",
    name: "Azzorre Ponta Delgada",
    city: "Azzorre Ponta Delgada",
    country: "PO",
    latitude: 37.7412,
    longitude: -25.6979,
    frequencies: ["124.850"],
    region: "Portogallo",
    volmetName: "Lisbon VOLMET / Shannon HF",
    atis: "123.900",
    isActive: true,
  },
  {
    icao: "LFPB",
    iata: "BVA",
    name: "Parigi Beauvais",
    city: "Parigi Beauvais",
    country: "FR",
    latitude: 49.4544,
    longitude: 2.1128,
    frequencies: ["126.000", "127.150"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "119.075",
    isActive: true,
  },
  {
    icao: "LFPO",
    iata: "ORY",
    name: "Parigi Orly",
    city: "Parigi Orly",
    country: "FR",
    latitude: 48.7233,
    longitude: 2.3794,
    frequencies: ["126.000", "127.150"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "132.700",
    isActive: true,
  },
  {
    icao: "LFML",
    iata: "MRS",
    name: "Marsiglia",
    city: "Marsiglia",
    country: "FR",
    latitude: 43.4393,
    longitude: 5.2214,
    frequencies: ["127.605"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "125.355",
    isActive: true,
  },
  {
    icao: "LFBO",
    iata: "TLS",
    name: "Tolosa",
    city: "Tolosa",
    country: "FR",
    latitude: 43.6291,
    longitude: 1.3638,
    frequencies: ["126.405"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "121.725",
    isActive: true,
  },
  {
    icao: "LFRS",
    iata: "NTE",
    name: "Nantes",
    city: "Nantes",
    country: "FR",
    latitude: 47.1532,
    longitude: -1.6107,
    frequencies: ["126.605"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "126.930",
    isActive: true,
  },
  {
    icao: "LFMN",
    iata: "NCE",
    name: "Nizza",
    city: "Nizza",
    country: "FR",
    latitude: 43.6584,
    longitude: 7.2159,
    frequencies: ["126.600"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "136.580",
    isActive: true,
  },
  {
    icao: "LFLL",
    iata: "LYS",
    name: "Lione",
    city: "Lione",
    country: "FR",
    latitude: 45.7256,
    longitude: 5.0811,
    frequencies: ["126.000", "127.150"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "121.800",
    isActive: true,
  },
  {
    icao: "LFBD",
    iata: "BOD",
    name: "Bordeaux",
    city: "Bordeaux",
    country: "FR",
    latitude: 44.8283,
    longitude: -0.7155,
    frequencies: ["126.405"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "131.155",
    isActive: true,
  },
  {
    icao: "LFBI",
    iata: "PIS",
    name: "Poitiers",
    city: "Poitiers",
    country: "FR",
    latitude: 46.5877,
    longitude: 0.3066,
    frequencies: ["126.000"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "121.780",
    isActive: true,
  },
  {
    icao: "LFBT",
    iata: "LDE",
    name: "Tarbes-Lourdes",
    city: "Tarbes-Lourdes",
    country: "FR",
    latitude: 43.1787,
    longitude: -0.0064,
    frequencies: ["127.005"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "125.955",
    isActive: true,
  },
  {
    icao: "LFBZ",
    iata: "BIQ",
    name: "Biarritz",
    city: "Biarritz",
    country: "FR",
    latitude: 43.4683,
    longitude: -1.5232,
    frequencies: ["127.005"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "128.230",
    isActive: true,
  },
  {
    icao: "LFMK",
    iata: "CCF",
    name: "Carcassonne",
    city: "Carcassonne",
    country: "FR",
    latitude: 43.216,
    longitude: 2.3063,
    frequencies: ["126.000"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "120.030",
    isActive: true,
  },
  {
    icao: "LFMP",
    iata: "PGF",
    name: "Perpignan",
    city: "Perpignan",
    country: "FR",
    latitude: 42.7404,
    longitude: 2.8707,
    frequencies: ["126.000"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "127.880",
    isActive: true,
  },
  {
    icao: "LFMO",
    iata: "FNI",
    name: "Nimes",
    city: "Nimes",
    country: "FR",
    latitude: 43.7574,
    longitude: 4.4163,
    frequencies: ["126.000"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "118.300",
    isActive: true,
  },
  {
    icao: "LFLS",
    iata: "GNB",
    name: "Grenoble",
    city: "Grenoble",
    country: "FR",
    latitude: 45.3629,
    longitude: 5.3294,
    frequencies: ["126.000"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "133.855",
    isActive: true,
  },
  {
    icao: "LFBH",
    iata: "LRH",
    name: "La Rochelle",
    city: "La Rochelle",
    country: "FR",
    latitude: 46.1792,
    longitude: -1.1953,
    frequencies: ["126.000"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "126.880",
    isActive: true,
  },
  {
    icao: "LFQQ",
    iata: "LIL",
    name: "Lille",
    city: "Lille",
    country: "FR",
    latitude: 50.5619,
    longitude: 3.0894,
    frequencies: ["125.155"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "119.330",
    isActive: true,
  },
  {
    icao: "LFBL",
    iata: "LIG",
    name: "Limoges",
    city: "Limoges",
    country: "FR",
    latitude: 45.8628,
    longitude: 1.1794,
    frequencies: ["126.000"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "128.080",
    isActive: true,
  },
  {
    icao: "LFSB",
    iata: "BSL",
    name: "Basilea EuroAirport",
    city: "Basilea EuroAirport",
    country: "FR",
    latitude: 47.5896,
    longitude: 7.5299,
    frequencies: ["127.205"],
    region: "Fr/CH/DE",
    volmetName: "Paris VOLMET / Frankfurt VOLMET",
    atis: "127.880",
    isActive: true,
  },
  {
    icao: "LFBG",
    iata: "EGC",
    name: "Bergerac",
    city: "Bergerac",
    country: "FR",
    latitude: 44.8253,
    longitude: 0.5187,
    frequencies: ["126.000"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "118.475",
    isActive: true,
  },
  {
    icao: "LFBV",
    iata: "BVE",
    name: "Brive-la-Gaillarde",
    city: "Brive-la-Gaillarde",
    country: "FR",
    latitude: 45.1508,
    longitude: 1.4692,
    frequencies: ["126.000"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "118.100",
    isActive: true,
  },
  {
    icao: "LFST",
    iata: "SXB",
    name: "Strasburgo",
    city: "Strasburgo",
    country: "FR",
    latitude: 48.5383,
    longitude: 7.6281,
    frequencies: ["126.000"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "119.275",
    isActive: true,
  },
  {
    icao: "LFOT",
    iata: "TUF",
    name: "Tours",
    city: "Tours",
    country: "FR",
    latitude: 47.4322,
    longitude: 0.7276,
    frequencies: ["126.000"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "123.500",
    isActive: true,
  },
  {
    icao: "LFSC",
    iata: "FSC",
    name: "Figari (Corsica)",
    city: "Figari (Corsica)",
    country: "FR",
    latitude: 41.5006,
    longitude: 9.0978,
    frequencies: ["126.000"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "119.450",
    isActive: true,
  },
  {
    icao: "LFDB",
    iata: "DLE",
    name: "Dole",
    city: "Dole",
    country: "FR",
    latitude: 47.0426,
    longitude: 5.4275,
    frequencies: ["126.000"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "119.325",
    isActive: true,
  },
  {
    icao: "LFCR",
    iata: "RDZ",
    name: "Rodez",
    city: "Rodez",
    country: "FR",
    latitude: 44.4079,
    longitude: 2.4827,
    frequencies: ["126.000"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "129.780",
    isActive: true,
  },
  {
    icao: "LFLB",
    iata: "CFE",
    name: "Clermont-Ferrand",
    city: "Clermont-Ferrand",
    country: "FR",
    latitude: 45.7867,
    longitude: 3.1658,
    frequencies: ["126.000"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "119.700",
    isActive: true,
  },
  {
    icao: "LFMU",
    iata: "BZR",
    name: "Beziers",
    city: "Beziers",
    country: "FR",
    latitude: 43.3235,
    longitude: 3.3539,
    frequencies: ["126.000"],
    region: "Francia",
    volmetName: "Paris VOLMET",
    atis: "127.530",
    isActive: true,
  },
  {
    icao: "EDDB",
    iata: "BER",
    name: "Berlino BER",
    city: "Berlino BER",
    country: "GE",
    latitude: 52.3667,
    longitude: 13.5033,
    frequencies: ["128.405"],
    region: "Germania",
    volmetName: "Frankfurt VOLMET",
    atis: "123.780",
    isActive: true,
  },
  {
    icao: "EDFH",
    iata: "HHN",
    name: "Frankfurt Hahn",
    city: "Frankfurt Hahn",
    country: "GE",
    latitude: 49.9487,
    longitude: 7.2639,
    frequencies: ["127.625"],
    region: "Germania",
    volmetName: "Frankfurt VOLMET",
    atis: "136.355",
    isActive: true,
  },
  {
    icao: "EDDK",
    iata: "CGN",
    name: "Colonia/Bonn",
    city: "Colonia/Bonn",
    country: "GE",
    latitude: 50.8659,
    longitude: 7.1427,
    frequencies: ["127.400"],
    region: "Germania",
    volmetName: "Frankfurt VOLMET",
    atis: "132.130",
    isActive: true,
  },
  {
    icao: "EDJA",
    iata: "FMM",
    name: "Memmingen",
    city: "Memmingen",
    country: "GE",
    latitude: 47.9888,
    longitude: 10.2395,
    frequencies: ["127.625"],
    region: "Germania",
    volmetName: "Frankfurt VOLMET",
    atis: "118.855",
    isActive: true,
  },
  {
    icao: "EDDN",
    iata: "NUE",
    name: "Norimberga",
    city: "Norimberga",
    country: "GE",
    latitude: 49.4987,
    longitude: 11.0669,
    frequencies: ["127.625"],
    region: "Germania",
    volmetName: "Frankfurt VOLMET",
    atis: "123.080",
    isActive: true,
  },
  {
    icao: "EDDW",
    iata: "BRE",
    name: "Bremen",
    city: "Bremen",
    country: "GE",
    latitude: 53.0475,
    longitude: 8.7867,
    frequencies: ["127.400"],
    region: "Germania",
    volmetName: "Frankfurt VOLMET",
    atis: "132.375",
    isActive: true,
  },
  {
    icao: "EDDH",
    iata: "HAM",
    name: "Amburgo",
    city: "Amburgo",
    country: "GE",
    latitude: 53.6304,
    longitude: 9.9882,
    frequencies: ["127.400"],
    region: "Germania",
    volmetName: "Frankfurt VOLMET",
    atis: "124.325",
    isActive: true,
  },
  {
    icao: "EDWE",
    iata: "NRN",
    name: "Weeze",
    city: "Weeze",
    country: "GE",
    latitude: 51.6024,
    longitude: 6.1422,
    frequencies: ["127.625"],
    region: "Germania",
    volmetName: "Frankfurt VOLMET",
    atis: "120.025",
    isActive: true,
  },
  {
    icao: "EDML",
    iata: "LBC",
    name: "Lubeck",
    city: "Lubeck",
    country: "GE",
    latitude: 53.8054,
    longitude: 10.7192,
    frequencies: ["127.625"],
    region: "Germania",
    volmetName: "Frankfurt VOLMET",
    atis: "118.050",
    isActive: true,
  },
  {
    icao: "EDNY",
    iata: "FDH",
    name: "Friedrichshafen",
    city: "Friedrichshafen",
    country: "GE",
    latitude: 47.6713,
    longitude: 9.5115,
    frequencies: ["130.480"],
    region: "Germania",
    volmetName: "Frankfurt VOLMET",
    atis: "129.605",
    isActive: true,
  },
  {
    icao: "EDDR",
    iata: "SCN",
    name: "Saarbrucken",
    city: "Saarbrucken",
    country: "GE",
    latitude: 49.2146,
    longitude: 7.1095,
    frequencies: ["127.625"],
    region: "Germania",
    volmetName: "Frankfurt VOLMET",
    atis: "125.625",
    isActive: true,
  },
  {
    icao: "EDLP",
    iata: "PAD",
    name: "Paderborn",
    city: "Paderborn",
    country: "GE",
    latitude: 51.6141,
    longitude: 8.6163,
    frequencies: ["127.625"],
    region: "Germania",
    volmetName: "Frankfurt VOLMET",
    atis: "125.950",
    isActive: true,
  },
  {
    icao: "EDDG",
    iata: "FMO",
    name: "Munster/Osnabruck",
    city: "Munster/Osnabruck",
    country: "GE",
    latitude: 52.1346,
    longitude: 7.6848,
    frequencies: ["127.625"],
    region: "Germania",
    volmetName: "Frankfurt VOLMET",
    atis: "127.180",
    isActive: true,
  },
  {
    icao: "EDFQ",
    iata: "FKB",
    name: "Karlsruhe/Baden-Baden",
    city: "Karlsruhe/Baden-Baden",
    country: "GE",
    latitude: 48.7794,
    longitude: 8.08,
    frequencies: ["127.625"],
    region: "Germania",
    volmetName: "Frankfurt VOLMET",
    atis: "124.175",
    isActive: true,
  },
  {
    icao: "EHAM",
    iata: "AMS",
    name: "Amsterdam Schiphol",
    city: "Amsterdam Schiphol",
    country: "OL",
    latitude: 52.3086,
    longitude: 4.7639,
    frequencies: ["126.200"],
    region: "Olanda",
    volmetName: "Amsterdam VOLMET",
    atis: "132.980",
    isActive: true,
  },
  {
    icao: "EHEH",
    iata: "EIN",
    name: "Eindhoven",
    city: "Eindhoven",
    country: "OL",
    latitude: 51.4501,
    longitude: 5.3746,
    frequencies: ["127.700"],
    region: "Olanda",
    volmetName: "Amsterdam VOLMET",
    atis: "126.030",
    isActive: true,
  },
  {
    icao: "EBBR",
    iata: "BRU",
    name: "Bruxelles",
    city: "Bruxelles",
    country: "BE",
    latitude: 50.9014,
    longitude: 4.4844,
    frequencies: ["127.805"],
    region: "Belgio",
    volmetName: "Brussels VOLMET",
    atis: "132.480",
    isActive: true,
  },
  {
    icao: "EBCI",
    iata: "CRL",
    name: "Charleroi",
    city: "Charleroi",
    country: "BE",
    latitude: 50.4592,
    longitude: 4.4538,
    frequencies: ["126.900"],
    region: "Belgio",
    volmetName: "Brussels VOLMET",
    atis: "134.630",
    isActive: true,
  },
  {
    icao: "LOWW",
    iata: "VIE",
    name: "Vienna",
    city: "Vienna",
    country: "AT",
    latitude: 48.1103,
    longitude: 16.5697,
    frequencies: ["126.005"],
    region: "Austria",
    volmetName: "Vienna VOLMET",
    atis: "128.200",
    isActive: true,
  },
  {
    icao: "LOWK",
    iata: "KLU",
    name: "Klagenfurt",
    city: "Klagenfurt",
    country: "AT",
    latitude: 46.6425,
    longitude: 14.3377,
    frequencies: ["126.825"],
    region: "Austria",
    volmetName: "Vienna VOLMET",
    atis: "119.775",
    isActive: true,
  },
  {
    icao: "LOWI",
    iata: "INN",
    name: "Innsbruck",
    city: "Innsbruck",
    country: "AT",
    latitude: 47.2602,
    longitude: 11.344,
    frequencies: ["126.825"],
    region: "Austria",
    volmetName: "Vienna VOLMET",
    atis: "119.175",
    isActive: true,
  },
  {
    icao: "LOWL",
    iata: "LNZ",
    name: "Linz",
    city: "Linz",
    country: "AT",
    latitude: 48.2332,
    longitude: 14.1875,
    frequencies: ["126.825"],
    region: "Austria",
    volmetName: "Vienna VOLMET",
    atis: "118.050",
    isActive: true,
  },
  {
    icao: "LOWS",
    iata: "SZG",
    name: "Salisburgo",
    city: "Salisburgo",
    country: "AT",
    latitude: 47.7933,
    longitude: 13.0043,
    frequencies: ["126.000"],
    region: "Austria",
    volmetName: "Vienna VOLMET",
    atis: "133.330",
    isActive: true,
  },
  {
    icao: "LSZH",
    iata: "ZRH",
    name: "Zurigo",
    city: "Zurigo",
    country: "SV",
    latitude: 47.4647,
    longitude: 8.5492,
    frequencies: ["127.500"],
    region: "Svizzera",
    volmetName: "Zurich VOLMET",
    atis: "128.025",
    isActive: true,
  },
  {
    icao: "LSGG",
    iata: "GVA",
    name: "Ginevra",
    city: "Ginevra",
    country: "SV",
    latitude: 46.2381,
    longitude: 6.1089,
    frequencies: ["126.805"],
    region: "Svizzera",
    volmetName: "Geneva VOLMET",
    atis: "131.325",
    isActive: true,
  },
  {
    icao: "LGAV",
    iata: "ATH",
    name: "Atene",
    city: "Atene",
    country: "GR",
    latitude: 37.9364,
    longitude: 23.9445,
    frequencies: ["127.800"],
    region: "Grecia",
    volmetName: "Athens VOLMET",
    atis: "136.125",
    isActive: true,
  },
  {
    icao: "LGTS",
    iata: "SKG",
    name: "Salonicco",
    city: "Salonicco",
    country: "GR",
    latitude: 40.5197,
    longitude: 22.9709,
    frequencies: ["127.800"],
    region: "Grecia",
    volmetName: "Athens VOLMET",
    atis: "126.225",
    isActive: true,
  },
  {
    icao: "LGKR",
    iata: "CFU",
    name: "Corfu",
    city: "Corfu",
    country: "GR",
    latitude: 39.6019,
    longitude: 19.9117,
    frequencies: ["127.800"],
    region: "Grecia",
    volmetName: "Athens VOLMET",
    atis: "126.350",
    isActive: true,
  },
  {
    icao: "LGIR",
    iata: "HER",
    name: "Heraklion (Creta)",
    city: "Heraklion (Creta)",
    country: "GR",
    latitude: 35.3397,
    longitude: 25.1803,
    frequencies: ["127.800"],
    region: "Grecia",
    volmetName: "Athens VOLMET",
    atis: "127.550",
    isActive: true,
  },
  {
    icao: "LGRP",
    iata: "RHO",
    name: "Rodi",
    city: "Rodi",
    country: "GR",
    latitude: 36.4054,
    longitude: 28.0862,
    frequencies: ["127.800"],
    region: "Grecia",
    volmetName: "Athens VOLMET",
    atis: "126.350",
    isActive: true,
  },
  {
    icao: "LGKL",
    iata: "KLX",
    name: "Kalamata",
    city: "Kalamata",
    country: "GR",
    latitude: 37.0683,
    longitude: 22.0255,
    frequencies: ["127.375"],
    region: "Grecia",
    volmetName: "Athens VOLMET",
    atis: "125.475",
    isActive: true,
  },
  {
    icao: "LGKF",
    iata: "EFL",
    name: "Cefalonia",
    city: "Cefalonia",
    country: "GR",
    latitude: 38.1201,
    longitude: 20.5005,
    frequencies: ["127.375"],
    region: "Grecia",
    volmetName: "Athens VOLMET",
    atis: "126.450",
    isActive: true,
  },
  {
    icao: "LGKO",
    iata: "KGS",
    name: "Kos",
    city: "Kos",
    country: "GR",
    latitude: 36.7933,
    longitude: 27.0917,
    frequencies: ["127.375"],
    region: "Grecia",
    volmetName: "Athens VOLMET",
    atis: "126.955",
    isActive: true,
  },
  {
    icao: "LGMK",
    iata: "JMK",
    name: "Mykonos",
    city: "Mykonos",
    country: "GR",
    latitude: 37.4351,
    longitude: 25.3481,
    frequencies: ["127.375"],
    region: "Grecia",
    volmetName: "Athens VOLMET",
    atis: "128.850",
    isActive: true,
  },
  {
    icao: "LGPZ",
    iata: "PVK",
    name: "Preveza",
    city: "Preveza",
    country: "GR",
    latitude: 38.9255,
    longitude: 20.7653,
    frequencies: ["127.375"],
    region: "Grecia",
    volmetName: "Athens VOLMET",
    atis: "120.025",
    isActive: true,
  },
  {
    icao: "LGSR",
    iata: "JTR",
    name: "Santorini",
    city: "Santorini",
    country: "GR",
    latitude: 36.3992,
    longitude: 25.4793,
    frequencies: ["127.375"],
    region: "Grecia",
    volmetName: "Athens VOLMET",
    atis: "126.450",
    isActive: true,
  },
  {
    icao: "LGSK",
    iata: "JSI",
    name: "Skiathos",
    city: "Skiathos",
    country: "GR",
    latitude: 39.1772,
    longitude: 23.5037,
    frequencies: ["127.375"],
    region: "Grecia",
    volmetName: "Athens VOLMET",
    atis: "122.400",
    isActive: true,
  },
  {
    icao: "LGZA",
    iata: "ZTH",
    name: "Zante",
    city: "Zante",
    country: "GR",
    latitude: 37.7509,
    longitude: 20.8843,
    frequencies: ["127.375"],
    region: "Grecia",
    volmetName: "Athens VOLMET",
    atis: "127.050",
    isActive: true,
  },
  {
    icao: "LGVO",
    iata: "VOL",
    name: "Volos",
    city: "Volos",
    country: "GR",
    latitude: 39.7838,
    longitude: 22.7943,
    frequencies: ["127.375"],
    region: "Grecia",
    volmetName: "Athens VOLMET",
    atis: "120.675",
    isActive: true,
  },
  {
    icao: "LGLM",
    iata: "LXS",
    name: "Lemno",
    city: "Lemno",
    country: "GR",
    latitude: 39.917,
    longitude: 25.2363,
    frequencies: ["127.375"],
    region: "Grecia",
    volmetName: "Athens VOLMET",
    atis: "119.075",
    isActive: true,
  },
  {
    icao: "LGPA",
    iata: "GPA",
    name: "Patras",
    city: "Patras",
    country: "GR",
    latitude: 38.1511,
    longitude: 21.4256,
    frequencies: ["127.375"],
    region: "Grecia",
    volmetName: "Athens VOLMET",
    atis: "119.075",
    isActive: true,
  },
  {
    icao: "LGSA",
    iata: "CHQ",
    name: "Chania (Creta)",
    city: "Chania (Creta)",
    country: "GR",
    latitude: 35.5317,
    longitude: 24.1497,
    frequencies: ["127.375"],
    region: "Grecia",
    volmetName: "Athens VOLMET",
    atis: "130.175",
    isActive: true,
  },
  {
    icao: "EPWA",
    iata: "WAW",
    name: "Varsavia Chopin",
    city: "Varsavia Chopin",
    country: "PO",
    latitude: 52.1657,
    longitude: 20.9671,
    frequencies: ["127.600"],
    region: "Polonia",
    volmetName: "Warsaw VOLMET",
    atis: "125.550",
    isActive: true,
  },
  {
    icao: "EPMO",
    iata: "WMI",
    name: "Varsavia Modlin",
    city: "Varsavia Modlin",
    country: "PO",
    latitude: 52.4511,
    longitude: 20.6518,
    frequencies: ["127.875"],
    region: "Polonia",
    volmetName: "Warsaw VOLMET",
    atis: "128.775",
    isActive: true,
  },
  {
    icao: "EPKK",
    iata: "KRK",
    name: "Cracovia",
    city: "Cracovia",
    country: "PO",
    latitude: 50.0778,
    longitude: 19.7848,
    frequencies: ["127.875"],
    region: "Polonia",
    volmetName: "Warsaw VOLMET",
    atis: "126.130",
    isActive: true,
  },
  {
    icao: "EPGD",
    iata: "GDN",
    name: "Danzica",
    city: "Danzica",
    country: "PO",
    latitude: 54.3776,
    longitude: 18.4662,
    frequencies: ["127.600"],
    region: "Polonia",
    volmetName: "Warsaw VOLMET",
    atis: "129.630",
    isActive: true,
  },
  {
    icao: "EPKT",
    iata: "KTW",
    name: "Katowice",
    city: "Katowice",
    country: "PO",
    latitude: 50.4743,
    longitude: 19.08,
    frequencies: ["127.875"],
    region: "Polonia",
    volmetName: "Warsaw VOLMET",
    atis: "120.230",
    isActive: true,
  },
  {
    icao: "EPPO",
    iata: "POZ",
    name: "Poznan",
    city: "Poznan",
    country: "PO",
    latitude: 52.421,
    longitude: 16.8263,
    frequencies: ["127.600"],
    region: "Polonia",
    volmetName: "Warsaw VOLMET",
    atis: "124.705",
    isActive: true,
  },
  {
    icao: "EPWR",
    iata: "WRO",
    name: "Wroclaw",
    city: "Wroclaw",
    country: "PO",
    latitude: 51.1027,
    longitude: 16.8858,
    frequencies: ["127.875"],
    region: "Polonia",
    volmetName: "Warsaw VOLMET",
    atis: "123.350",
    isActive: true,
  },
  {
    icao: "EPBY",
    iata: "BZG",
    name: "Bydgoszcz",
    city: "Bydgoszcz",
    country: "PO",
    latitude: 53.0968,
    longitude: 17.9777,
    frequencies: ["127.875"],
    region: "Polonia",
    volmetName: "Warsaw VOLMET",
    atis: "126.575",
    isActive: true,
  },
  {
    icao: "EPLB",
    iata: "LUZ",
    name: "Lublino",
    city: "Lublino",
    country: "PO",
    latitude: 51.2403,
    longitude: 22.7136,
    frequencies: ["127.875"],
    region: "Polonia",
    volmetName: "Warsaw VOLMET",
    atis: "119.475",
    isActive: true,
  },
  {
    icao: "EPLL",
    iata: "LCJ",
    name: "Lodz",
    city: "Lodz",
    country: "PO",
    latitude: 51.7219,
    longitude: 19.3981,
    frequencies: ["127.875"],
    region: "Polonia",
    volmetName: "Warsaw VOLMET",
    atis: "135.680",
    isActive: true,
  },
  {
    icao: "EPRZ",
    iata: "RZE",
    name: "Rzeszow",
    city: "Rzeszow",
    country: "PO",
    latitude: 50.11,
    longitude: 22.019,
    frequencies: ["127.875"],
    region: "Polonia",
    volmetName: "Warsaw VOLMET",
    atis: "124.955",
    isActive: true,
  },
  {
    icao: "EPSC",
    iata: "SZZ",
    name: "Szczecin",
    city: "Szczecin",
    country: "PO",
    latitude: 53.5847,
    longitude: 14.9022,
    frequencies: ["127.875"],
    region: "Polonia",
    volmetName: "Warsaw VOLMET",
    atis: "126.850",
    isActive: true,
  },
  {
    icao: "EPOM",
    iata: "SZY",
    name: "Olsztyn",
    city: "Olsztyn",
    country: "PO",
    latitude: 53.4819,
    longitude: 20.9378,
    frequencies: ["127.875"],
    region: "Polonia",
    volmetName: "Warsaw VOLMET",
    atis: "119.375",
    isActive: true,
  },
  {
    icao: "LROP",
    iata: "OTP",
    name: "Bucarest Otopeni",
    city: "Bucarest Otopeni",
    country: "RO",
    latitude: 44.5711,
    longitude: 26.085,
    frequencies: ["126.800"],
    region: "Romania",
    volmetName: "Bucharest VOLMET",
    atis: "118.500",
    isActive: true,
  },
  {
    icao: "LRBS",
    iata: "BBU",
    name: "Bucarest Baneasa",
    city: "Bucarest Baneasa",
    country: "RO",
    latitude: 44.5032,
    longitude: 26.1021,
    frequencies: ["127.750"],
    region: "Romania",
    volmetName: "Bucharest VOLMET",
    atis: "125.600",
    isActive: true,
  },
  {
    icao: "LRCL",
    iata: "CLJ",
    name: "Cluj-Napoca",
    city: "Cluj-Napoca",
    country: "RO",
    latitude: 46.7852,
    longitude: 23.6862,
    frequencies: ["127.750"],
    region: "Romania",
    volmetName: "Bucharest VOLMET",
    atis: "125.525",
    isActive: true,
  },
  {
    icao: "LRIA",
    iata: "IAS",
    name: "Iasi",
    city: "Iasi",
    country: "RO",
    latitude: 47.1783,
    longitude: 27.6206,
    frequencies: ["127.750"],
    region: "Romania",
    volmetName: "Bucharest VOLMET",
    atis: "119.900",
    isActive: true,
  },
  {
    icao: "LHBP",
    iata: "BUD",
    name: "Budapest",
    city: "Budapest",
    country: "UN",
    latitude: 47.4298,
    longitude: 19.2611,
    frequencies: ["127.405"],
    region: "Ungheria",
    volmetName: "Budapest VOLMET",
    atis: "132.380",
    isActive: true,
  },
  {
    icao: "LKPR",
    iata: "PRG",
    name: "Praga",
    city: "Praga",
    country: "CE",
    latitude: 50.1008,
    longitude: 14.26,
    frequencies: ["128.605"],
    region: "Cechia",
    volmetName: "Prague VOLMET",
    atis: "122.160",
    isActive: true,
  },
  {
    icao: "LKTB",
    iata: "BRQ",
    name: "Brno",
    city: "Brno",
    country: "CE",
    latitude: 49.1513,
    longitude: 16.6944,
    frequencies: ["125.525"],
    region: "Cechia",
    volmetName: "Prague VOLMET",
    atis: "131.105",
    isActive: true,
  },
  {
    icao: "LKMT",
    iata: "OSR",
    name: "Ostrava",
    city: "Ostrava",
    country: "CE",
    latitude: 49.6963,
    longitude: 18.1111,
    frequencies: ["126.200"],
    region: "Cechia",
    volmetName: "Prague VOLMET",
    atis: "118.055",
    isActive: true,
  },
  {
    icao: "LKPD",
    iata: "PED",
    name: "Pardubice",
    city: "Pardubice",
    country: "CE",
    latitude: 50.0134,
    longitude: 15.7386,
    frequencies: ["125.525"],
    region: "Cechia",
    volmetName: "Prague VOLMET",
    atis: "118.750",
    isActive: true,
  },
  {
    icao: "LZIB",
    iata: "BTS",
    name: "Bratislava",
    city: "Bratislava",
    country: "SL",
    latitude: 48.1702,
    longitude: 17.2127,
    frequencies: ["126.200"],
    region: "Slovacchia",
    volmetName: "Bratislava VOLMET",
    atis: "133.880",
    isActive: true,
  },
  {
    icao: "LZKZ",
    iata: "KSC",
    name: "Kosice",
    city: "Kosice",
    country: "SL",
    latitude: 48.6632,
    longitude: 21.2411,
    frequencies: ["126.200"],
    region: "Slovacchia",
    volmetName: "Bratislava VOLMET",
    atis: "133.730",
    isActive: true,
  },
  {
    icao: "LZPP",
    iata: "TAT",
    name: "Poprad",
    city: "Poprad",
    country: "SL",
    latitude: 49.0736,
    longitude: 20.2411,
    frequencies: ["126.000"],
    region: "Slovacchia",
    volmetName: "Bratislava VOLMET",
    atis: "119.550",
    isActive: true,
  },
  {
    icao: "LDZA",
    iata: "ZAG",
    name: "Zagabria",
    city: "Zagabria",
    country: "CR",
    latitude: 45.7429,
    longitude: 16.0688,
    frequencies: ["127.800"],
    region: "Croazia",
    volmetName: "Zagreb VOLMET",
    atis: "124.575",
    isActive: true,
  },
  {
    icao: "LDSP",
    iata: "SPU",
    name: "Spalato",
    city: "Spalato",
    country: "CR",
    latitude: 43.5389,
    longitude: 16.298,
    frequencies: ["126.350"],
    region: "Croazia",
    volmetName: "Zagreb VOLMET",
    atis: "119.325",
    isActive: true,
  },
  {
    icao: "LDDU",
    iata: "DBV",
    name: "Dubrovnik",
    city: "Dubrovnik",
    country: "CR",
    latitude: 42.5614,
    longitude: 18.2682,
    frequencies: ["127.800"],
    region: "Croazia",
    volmetName: "Zagreb VOLMET",
    atis: "118.425",
    isActive: true,
  },
  {
    icao: "LDZD",
    iata: "ZAD",
    name: "Zadar",
    city: "Zadar",
    country: "CR",
    latitude: 44.1083,
    longitude: 15.3467,
    frequencies: ["126.350"],
    region: "Croazia",
    volmetName: "Zagreb VOLMET",
    atis: "119.150",
    isActive: true,
  },
  {
    icao: "LDPL",
    iata: "PUY",
    name: "Pola",
    city: "Pola",
    country: "CR",
    latitude: 44.8935,
    longitude: 13.9222,
    frequencies: ["127.800"],
    region: "Croazia",
    volmetName: "Zagreb VOLMET",
    atis: "129.150",
    isActive: true,
  },
  {
    icao: "LDRI",
    iata: "RJK",
    name: "Rijeka",
    city: "Rijeka",
    country: "CR",
    latitude: 45.2169,
    longitude: 14.5703,
    frequencies: ["126.350"],
    region: "Croazia",
    volmetName: "Zagreb VOLMET",
    atis: "119.075",
    isActive: true,
  },
  {
    icao: "LDOS",
    iata: "OSI",
    name: "Osijek",
    city: "Osijek",
    country: "CR",
    latitude: 45.4627,
    longitude: 18.8102,
    frequencies: ["126.350"],
    region: "Croazia",
    volmetName: "Zagreb VOLMET",
    atis: "119.675",
    isActive: true,
  },
  {
    icao: "LYBE",
    iata: "BEG",
    name: "Belgrado",
    city: "Belgrado",
    country: "RS",
    latitude: 44.8184,
    longitude: 20.3091,
    frequencies: ["126.350"],
    region: "Serbia",
    volmetName: "Belgrade VOLMET",
    atis: "126.050",
    isActive: true,
  },
  {
    icao: "LYNI",
    iata: "INI",
    name: "Nis",
    city: "Nis",
    country: "RS",
    latitude: 43.3373,
    longitude: 21.8538,
    frequencies: ["126.400"],
    region: "Serbia",
    volmetName: "Belgrade VOLMET",
    atis: "121.525",
    isActive: true,
  },
  {
    icao: "LBSF",
    iata: "SOF",
    name: "Sofia",
    city: "Sofia",
    country: "BG",
    latitude: 42.6967,
    longitude: 23.4114,
    frequencies: ["126.350"],
    region: "Bulgaria",
    volmetName: "Sofia VOLMET",
    atis: "128.525",
    isActive: true,
  },
  {
    icao: "LBBG",
    iata: "BOJ",
    name: "Burgas",
    city: "Burgas",
    country: "BG",
    latitude: 42.5696,
    longitude: 27.5152,
    frequencies: ["126.605"],
    region: "Bulgaria",
    volmetName: "Sofia VOLMET",
    atis: "126.980",
    isActive: true,
  },
  {
    icao: "LBPD",
    iata: "PDV",
    name: "Plovdiv",
    city: "Plovdiv",
    country: "BG",
    latitude: 42.0678,
    longitude: 24.8508,
    frequencies: ["126.605"],
    region: "Bulgaria",
    volmetName: "Sofia VOLMET",
    atis: "127.205",
    isActive: true,
  },
  {
    icao: "LBWN",
    iata: "VAR",
    name: "Varna",
    city: "Varna",
    country: "BG",
    latitude: 43.2321,
    longitude: 27.8251,
    frequencies: ["126.350"],
    region: "Bulgaria",
    volmetName: "Sofia VOLMET",
    atis: "119.200",
    isActive: true,
  },
  {
    icao: "LATI",
    iata: "TIA",
    name: "Tirana",
    city: "Tirana",
    country: "AL",
    latitude: 41.4147,
    longitude: 19.7206,
    frequencies: ["126.350"],
    region: "Albania",
    volmetName: "Belgrade VOLMET",
    atis: "128.875",
    isActive: true,
  },
  {
    icao: "LYPG",
    iata: "TGD",
    name: "Podgorica",
    city: "Podgorica",
    country: "ME",
    latitude: 42.3594,
    longitude: 19.2519,
    frequencies: ["126.400"],
    region: "Montenegro",
    volmetName: "Belgrade VOLMET",
    atis: "121.850",
    isActive: true,
  },
  {
    icao: "LQSA",
    iata: "SJJ",
    name: "Sarajevo",
    city: "Sarajevo",
    country: "BA",
    latitude: 43.8246,
    longitude: 18.3315,
    frequencies: ["126.350"],
    region: "Bosnia",
    volmetName: "Belgrade VOLMET",
    atis: "127.975",
    isActive: true,
  },
  {
    icao: "LQBK",
    iata: "BNX",
    name: "Banja Luka",
    city: "Banja Luka",
    country: "BA",
    latitude: 44.9414,
    longitude: 17.2975,
    frequencies: ["135.775"],
    region: "Bosnia",
    volmetName: "Belgrade VOLMET",
    atis: "120.725",
    isActive: true,
  },
  {
    icao: "EVRA",
    iata: "RIX",
    name: "Riga",
    city: "Riga",
    country: "LE",
    latitude: 56.9236,
    longitude: 23.9711,
    frequencies: ["127.655"],
    region: "Lettonia",
    volmetName: "Riga VOLMET",
    atis: "120.180",
    isActive: true,
  },
  {
    icao: "EYVI",
    iata: "VNO",
    name: "Vilnius",
    city: "Vilnius",
    country: "LI",
    latitude: 54.6341,
    longitude: 25.2858,
    frequencies: ["127.605"],
    region: "Lituania",
    volmetName: "Vilnius VOLMET",
    atis: "131.275",
    isActive: true,
  },
  {
    icao: "EYKA",
    iata: "KUN",
    name: "Kaunas",
    city: "Kaunas",
    country: "LI",
    latitude: 54.9639,
    longitude: 24.0848,
    frequencies: ["126.100"],
    region: "Lituania",
    volmetName: "Vilnius VOLMET",
    atis: "129.055",
    isActive: true,
  },
  {
    icao: "EYPA",
    iata: "PLQ",
    name: "Palanga",
    city: "Palanga",
    country: "LI",
    latitude: 55.9733,
    longitude: 21.0939,
    frequencies: ["126.100"],
    region: "Lituania",
    volmetName: "Vilnius VOLMET",
    atis: "127.805",
    isActive: true,
  },
  {
    icao: "EETN",
    iata: "TLL",
    name: "Tallinn",
    city: "Tallinn",
    country: "EE",
    latitude: 59.4133,
    longitude: 24.8328,
    frequencies: ["128.400"],
    region: "Estonia",
    volmetName: "Tallinn VOLMET",
    atis: "123.800",
    isActive: true,
  },
  {
    icao: "ENGM",
    iata: "OSL",
    name: "Oslo Gardermoen",
    city: "Oslo Gardermoen",
    country: "NO",
    latitude: 60.1939,
    longitude: 11.1004,
    frequencies: ["128.600"],
    region: "Norvegia",
    volmetName: "Oslo VOLMET",
    atis: "126.125",
    isActive: true,
  },
  {
    icao: "ENTO",
    iata: "TRF",
    name: "Oslo Sandefjord",
    city: "Oslo Sandefjord",
    country: "NO",
    latitude: 59.1867,
    longitude: 10.2586,
    frequencies: ["126.000"],
    region: "Norvegia",
    volmetName: "Oslo VOLMET",
    atis: "119.075",
    isActive: true,
  },
  {
    icao: "ESSA",
    iata: "ARN",
    name: "Stoccolma Arlanda",
    city: "Stoccolma Arlanda",
    country: "SV",
    latitude: 59.6519,
    longitude: 17.9186,
    frequencies: ["127.625", "126.800"],
    region: "Svezia",
    volmetName: "Stockholm VOLMET",
    atis: "136.150",
    isActive: true,
  },
  {
    icao: "ESGG",
    iata: "GOT",
    name: "Goteborg",
    city: "Goteborg",
    country: "SV",
    latitude: 57.6628,
    longitude: 12.2798,
    frequencies: ["127.005"],
    region: "Svezia",
    volmetName: "Stockholm VOLMET",
    atis: "118.380",
    isActive: true,
  },
  {
    icao: "ESMS",
    iata: "MMX",
    name: "Malmo",
    city: "Malmo",
    country: "SV",
    latitude: 55.5363,
    longitude: 13.3762,
    frequencies: ["127.005"],
    region: "Svezia",
    volmetName: "Stockholm VOLMET",
    atis: "129.280",
    isActive: true,
  },
  {
    icao: "ESOW",
    iata: "VST",
    name: "Vasteras",
    city: "Vasteras",
    country: "SV",
    latitude: 59.5894,
    longitude: 16.6336,
    frequencies: ["127.625"],
    region: "Svezia",
    volmetName: "Stockholm VOLMET",
    atis: "119.200",
    isActive: true,
  },
  {
    icao: "ESMX",
    iata: "VXO",
    name: "Vaxjo",
    city: "Vaxjo",
    country: "SV",
    latitude: 56.9291,
    longitude: 14.728,
    frequencies: ["127.625"],
    region: "Svezia",
    volmetName: "Stockholm VOLMET",
    atis: "120.125",
    isActive: true,
  },
  {
    icao: "ESUD",
    iata: "SKE",
    name: "Skelleftea",
    city: "Skelleftea",
    country: "SV",
    latitude: 64.6248,
    longitude: 21.0769,
    frequencies: ["127.625"],
    region: "Svezia",
    volmetName: "Stockholm VOLMET",
    atis: "121.250",
    isActive: true,
  },
  {
    icao: "ESOE",
    iata: "ORB",
    name: "Orebro",
    city: "Orebro",
    country: "SV",
    latitude: 59.2237,
    longitude: 15.038,
    frequencies: ["127.625"],
    region: "Svezia",
    volmetName: "Stockholm VOLMET",
    atis: "119.025",
    isActive: true,
  },
  {
    icao: "EKCH",
    iata: "CPH",
    name: "Copenaghen",
    city: "Copenaghen",
    country: "DA",
    latitude: 55.618,
    longitude: 12.656,
    frequencies: ["127.005"],
    region: "Danimarca",
    volmetName: "Copenhagen VOLMET",
    atis: "122.750",
    isActive: true,
  },
  {
    icao: "EKAH",
    iata: "AAR",
    name: "Aarhus",
    city: "Aarhus",
    country: "DA",
    latitude: 56.2999,
    longitude: 10.619,
    frequencies: ["127.750"],
    region: "Danimarca",
    volmetName: "Copenhagen VOLMET",
    atis: "119.675",
    isActive: true,
  },
  {
    icao: "EFHK",
    iata: "HEL",
    name: "Helsinki",
    city: "Helsinki",
    country: "FI",
    latitude: 60.3172,
    longitude: 24.9633,
    frequencies: ["128.400"],
    region: "Finlandia",
    volmetName: "Helsinki VOLMET",
    atis: "135.075",
    isActive: true,
  },
  {
    icao: "EFRO",
    iata: "RVN",
    name: "Rovaniemi",
    city: "Rovaniemi",
    country: "FI",
    latitude: 66.5648,
    longitude: 25.8304,
    frequencies: ["128.375"],
    region: "Finlandia",
    volmetName: "Helsinki VOLMET",
    atis: "119.425",
    isActive: true,
  },
  {
    icao: "EFLP",
    iata: "LPP",
    name: "Lappeenranta",
    city: "Lappeenranta",
    country: "FI",
    latitude: 61.0446,
    longitude: 28.1444,
    frequencies: ["128.375"],
    region: "Finlandia",
    volmetName: "Helsinki VOLMET",
    atis: "136.325",
    isActive: true,
  },
  {
    icao: "ELLX",
    iata: "LUX",
    name: "Lussemburgo",
    city: "Lussemburgo",
    country: "LU",
    latitude: 49.6233,
    longitude: 6.2044,
    frequencies: ["127.805"],
    region: "Lussemburgo",
    volmetName: "Brussels / Frankfurt VOLMET",
    atis: "134.755",
    isActive: true,
  },
  {
    icao: "LMML",
    iata: "MLA",
    name: "Malta",
    city: "Malta",
    country: "MT",
    latitude: 35.8574,
    longitude: 14.4775,
    frequencies: ["126.800"],
    region: "Malta",
    volmetName: "Malta VOLMET",
    atis: "127.400",
    isActive: true,
  },
  {
    icao: "LCPH",
    iata: "PFO",
    name: "Paphos",
    city: "Paphos",
    country: "CI",
    latitude: 34.718,
    longitude: 32.4857,
    frequencies: ["127.500"],
    region: "Cipro",
    volmetName: "Nicosia VOLMET",
    atis: "127.050",
    isActive: true,
  },
  {
    icao: "LCLK",
    iata: "LCA",
    name: "Larnaca",
    city: "Larnaca",
    country: "CI",
    latitude: 34.8751,
    longitude: 33.6249,
    frequencies: ["127.200"],
    region: "Cipro",
    volmetName: "Nicosia VOLMET",
    atis: "126.550",
    isActive: true,
  },
  {
    icao: "LTFM",
    iata: "IST",
    name: "Istanbul",
    city: "Istanbul",
    country: "TU",
    latitude: 41.2753,
    longitude: 28.7519,
    frequencies: ["126.450", "127.650"],
    region: "Turchia",
    volmetName: "Istanbul VOLMET",
    atis: "127.600",
    isActive: true,
  },
  {
    icao: "LTBJ",
    iata: "ADB",
    name: "Bodrum",
    city: "Bodrum",
    country: "TU",
    latitude: 38.1214,
    longitude: 27.157,
    frequencies: ["126.450"],
    region: "Turchia",
    volmetName: "Istanbul VOLMET",
    atis: "126.100",
    isActive: true,
  },
  {
    icao: "LTBS",
    iata: "DLM",
    name: "Dalaman",
    city: "Dalaman",
    country: "TU",
    latitude: 36.7131,
    longitude: 28.7925,
    frequencies: ["127.400"],
    region: "Turchia",
    volmetName: "Istanbul VOLMET",
    atis: "127.350",
    isActive: true,
  },
  {
    icao: "LLBG",
    iata: "TLV",
    name: "Tel Aviv Ben Gurion",
    city: "Tel Aviv Ben Gurion",
    country: "IS",
    latitude: 32.0114,
    longitude: 34.8867,
    frequencies: ["126.850"],
    region: "Israele",
    volmetName: "Tel Aviv VOLMET",
    atis: "132.500",
    isActive: true,
  },
  {
    icao: "OJAI",
    iata: "AMM",
    name: "Amman",
    city: "Amman",
    country: "GI",
    latitude: 31.7226,
    longitude: 35.9932,
    frequencies: ["126.000"],
    region: "Giordania",
    volmetName: "Amman VOLMET",
    atis: "127.600",
    isActive: true,
  },
  {
    icao: "OJAQ",
    iata: "AQJ",
    name: "Aqaba",
    city: "Aqaba",
    country: "GI",
    latitude: 29.6116,
    longitude: 35.0181,
    frequencies: ["127.000"],
    region: "Giordania",
    volmetName: "Amman VOLMET",
    atis: "118.300",
    isActive: true,
  },
  {
    icao: "GMME",
    iata: "RBA",
    name: "Rabat",
    city: "Rabat",
    country: "MA",
    latitude: 34.0515,
    longitude: -6.7515,
    frequencies: ["127.600"],
    region: "Marocco",
    volmetName: "Casablanca VOLMET",
    atis: "127.700",
    isActive: true,
  },
  {
    icao: "GMMX",
    iata: "RAK",
    name: "Marrakech",
    city: "Marrakech",
    country: "MA",
    latitude: 31.6069,
    longitude: -8.0363,
    frequencies: ["127.600"],
    region: "Marocco",
    volmetName: "Casablanca VOLMET",
    atis: "121.950",
    isActive: true,
  },
  {
    icao: "GMFO",
    iata: "OUD",
    name: "Oujda",
    city: "Oujda",
    country: "MA",
    latitude: 34.7872,
    longitude: -1.924,
    frequencies: ["127.600"],
    region: "Marocco",
    volmetName: "Casablanca VOLMET",
    atis: "121.600",
    isActive: true,
  },
  {
    icao: "GMMN",
    iata: "CMN",
    name: "Casablanca",
    city: "Casablanca",
    country: "MA",
    latitude: 33.3675,
    longitude: -7.5898,
    frequencies: ["127.150"],
    region: "Marocco",
    volmetName: "Casablanca VOLMET",
    atis: "127.700",
    isActive: true,
  },
  {
    icao: "GMFK",
    iata: "ERH",
    name: "Errachidia",
    city: "Errachidia",
    country: "MA",
    latitude: 31.9475,
    longitude: -4.3983,
    frequencies: ["127.150"],
    region: "Marocco",
    volmetName: "Casablanca VOLMET",
    atis: "118.300",
    isActive: true,
  },
  {
    icao: "GMFE",
    iata: "FEZ",
    name: "Fez",
    city: "Fez",
    country: "MA",
    latitude: 33.9273,
    longitude: -4.9779,
    frequencies: ["127.150"],
    region: "Marocco",
    volmetName: "Casablanca VOLMET",
    atis: "126.700",
    isActive: true,
  },
  {
    icao: "GMAG",
    iata: "AGA",
    name: "Agadir",
    city: "Agadir",
    country: "MA",
    latitude: 30.325,
    longitude: -9.4131,
    frequencies: ["127.150"],
    region: "Marocco",
    volmetName: "Casablanca VOLMET",
    atis: "121.200",
    isActive: true,
  },
  {
    icao: "GMTN",
    iata: "TNG",
    name: "Tangeri",
    city: "Tangeri",
    country: "MA",
    latitude: 35.7269,
    longitude: -5.9169,
    frequencies: ["127.150"],
    region: "Marocco",
    volmetName: "Casablanca VOLMET",
    atis: "124.575",
    isActive: true,
  },
  {
    icao: "GMMB",
    iata: "BEM",
    name: "Beni Mellal",
    city: "Beni Mellal",
    country: "MA",
    latitude: 32.4019,
    longitude: -6.3159,
    frequencies: ["127.150"],
    region: "Marocco",
    volmetName: "Casablanca VOLMET",
    atis: "119.800",
    isActive: true,
  },
  {
    icao: "GMNI",
    iata: "NDR",
    name: "Nador",
    city: "Nador",
    country: "MA",
    latitude: 34.9888,
    longitude: -3.0282,
    frequencies: ["127.150"],
    region: "Marocco",
    volmetName: "Casablanca VOLMET",
    atis: "119.850",
    isActive: true,
  },
  {
    icao: "GMMO",
    iata: "OZZ",
    name: "Ouarzazate",
    city: "Ouarzazate",
    country: "MA",
    latitude: 30.9391,
    longitude: -6.9094,
    frequencies: ["127.150"],
    region: "Marocco",
    volmetName: "Casablanca VOLMET",
    atis: "119.000",
    isActive: true,
  },
  {
    icao: "GMMS",
    iata: "ESU",
    name: "Essaouira",
    city: "Essaouira",
    country: "MA",
    latitude: 31.3975,
    longitude: -9.6817,
    frequencies: ["127.150"],
    region: "Marocco",
    volmetName: "Casablanca VOLMET",
    atis: "118.300",
    isActive: true,
  },
  {
    icao: "GMAD",
    iata: "VIL",
    name: "Dakhla",
    city: "Dakhla",
    country: "MA",
    latitude: 23.7183,
    longitude: -15.932,
    frequencies: ["127.600"],
    region: "Marocco",
    volmetName: "Casablanca VOLMET",
    atis: "127.750",
    isActive: true,
  },
  {
    icao: "GMMH",
    iata: "TTU",
    name: "Tetouan",
    city: "Tetouan",
    country: "MA",
    latitude: 35.5943,
    longitude: -5.32,
    frequencies: ["127.150"],
    region: "Marocco",
    volmetName: "Casablanca VOLMET",
    atis: "120.900",
    isActive: true,
  },
];
