import { Volmet } from "../../volmet/entities/volmet.entity";

export const VOLMET_DATA: Partial<Volmet>[] = [
  {
    icao: "BKPR",
    iata: "PRN",
    name: "Adem Jashari",
    city: "Adem Jashari",
    country: "RS",
    latitude: 42.572778,
    longitude: 21.035833,
    frequencies: ["126.425"],
    region: "Kosovo",
    volmetName: "Belgrade VOLMET",
    atis: "134.385",
    isActive: true,
  },
  {
    icao: "DTMB",
    iata: "MIR",
    name: "Habib Bourguiba",
    city: "Habib Bourguiba",
    country: "TN",
    latitude: 35.758056,
    longitude: 10.754722,
    frequencies: ["126.450"],
    region: "Tunisia",
    volmetName: "Tunis VOLMET",
    atis: "128.12",
    isActive: true,
  },
  {
    icao: "DTTA",
    iata: "TUN",
    name: "Carthage",
    city: "Carthage",
    country: "TN",
    latitude: 36.851111,
    longitude: 10.226944,
    frequencies: ["126.450"],
    region: "Tunisia",
    volmetName: "Tunis VOLMET",
    atis: "118.67",
    isActive: true,
  },
  {
    icao: "DTTB",
    name: "DTTB",
    city: "DTTB",
    country: "TN",
    frequencies: ["126.450"],
    region: "Tunisia",
    volmetName: "Tunis VOLMET",
    isActive: true,
  },
  {
    icao: "DTTJ",
    iata: "DJE",
    name: "Zarzis",
    city: "Zarzis",
    country: "TN",
    latitude: 33.875556,
    longitude: 10.777222,
    frequencies: ["126.450"],
    region: "Tunisia",
    volmetName: "Tunis VOLMET",
    atis: "124.52",
    isActive: true,
  },
  {
    icao: "EBBR",
    iata: "BRU",
    name: "Brussels Natl",
    city: "Brussels Natl",
    country: "BE",
    latitude: 50.901389,
    longitude: 4.484444,
    frequencies: ["127.000"],
    region: "Belgium",
    volmetName: "Amsterdam VOLMET",
    atis: "110.6",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EBCI",
    iata: "CRL",
    name: "Brussels South",
    city: "Brussels South",
    country: "BE",
    latitude: 50.46,
    longitude: 4.452778,
    frequencies: ["127.000"],
    region: "Belgium",
    volmetName: "Amsterdam VOLMET",
    atis: "115.7",
    isActive: true,
  },
  {
    icao: "EBLG",
    iata: "LGG",
    name: "Liege",
    city: "Liege",
    country: "BE",
    latitude: 50.636389,
    longitude: 5.442778,
    frequencies: ["127.000"],
    region: "Belgium",
    volmetName: "Amsterdam VOLMET",
    atis: "126.255",
    isActive: true,
  },
  {
    icao: "EDDB",
    iata: "BER",
    name: "Berlin Brandenburg",
    city: "Berlin Brandenburg",
    country: "DE",
    latitude: 52.362247,
    longitude: 13.500672,
    frequencies: ["126.425"],
    region: "Germany",
    volmetName: "Frankfurt VOLMET",
    atis: "123.78",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EDDC",
    iata: "DRS",
    name: "Dresden",
    city: "Dresden",
    country: "DE",
    latitude: 51.134344,
    longitude: 13.768,
    frequencies: ["126.425"],
    region: "Germany",
    volmetName: "Frankfurt VOLMET",
    atis: "118.88",
    isActive: true,
  },
  {
    icao: "EDDF",
    iata: "FRA",
    name: "Frankfurt Main",
    city: "Frankfurt Main",
    country: "DE",
    latitude: 50.033306,
    longitude: 8.570456,
    frequencies: ["126.425"],
    region: "Germany",
    volmetName: "Frankfurt VOLMET",
    atis: "118.03",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EDDH",
    iata: "HAM",
    name: "Hamburg",
    city: "Hamburg",
    country: "DE",
    latitude: 53.630389,
    longitude: 9.988228,
    frequencies: ["127.000"],
    region: "Germany",
    volmetName: "Amsterdam VOLMET",
    atis: "124.32",
    isActive: true,
  },
  {
    icao: "EDDK",
    iata: "CGN",
    name: "Cologne Bonn",
    city: "Cologne Bonn",
    country: "DE",
    latitude: 50.865917,
    longitude: 7.142744,
    frequencies: ["126.425"],
    region: "Germany",
    volmetName: "Frankfurt VOLMET",
    atis: "112.15",
    isActive: true,
  },
  {
    icao: "EDDL",
    iata: "DUS",
    name: "Duesseldorf",
    city: "Duesseldorf",
    country: "DE",
    latitude: 51.280925,
    longitude: 6.757311,
    frequencies: ["126.425"],
    region: "Germany",
    volmetName: "Frankfurt VOLMET",
    atis: "123.78",
    isActive: true,
  },
  {
    icao: "EDDM",
    iata: "MUC",
    name: "Munich",
    city: "Munich",
    country: "DE",
    latitude: 48.353783,
    longitude: 11.786086,
    frequencies: ["126.425"],
    region: "Germany",
    volmetName: "Frankfurt VOLMET",
    atis: "123.13",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EDDN",
    iata: "NUE",
    name: "Nuernberg",
    city: "Nuernberg",
    country: "DE",
    latitude: 49.4987,
    longitude: 11.078008,
    frequencies: ["126.425"],
    region: "Germany",
    volmetName: "Frankfurt VOLMET",
    atis: "123.08",
    isActive: true,
  },
  {
    icao: "EDDS",
    iata: "STR",
    name: "Stuttgart",
    city: "Stuttgart",
    country: "DE",
    latitude: 48.689878,
    longitude: 9.221964,
    frequencies: ["126.425"],
    region: "Germany",
    volmetName: "Frankfurt VOLMET",
    atis: "126.13",
    isActive: true,
  },
  {
    icao: "EDLV",
    iata: "NRN",
    name: "Niederrhein",
    city: "Niederrhein",
    country: "DE",
    latitude: 51.602414,
    longitude: 6.142172,
    frequencies: ["127.000"],
    region: "Germany",
    volmetName: "Amsterdam VOLMET",
    atis: "124.455",
    isActive: true,
  },
  {
    icao: "EETN",
    iata: "TLL",
    name: "Lennart Meri",
    city: "Lennart Meri",
    country: "EE",
    latitude: 59.413333,
    longitude: 24.8325,
    frequencies: ["126.425"],
    region: "Estonia",
    volmetName: "Helsinki VOLMET",
    atis: "124.88",
    isActive: true,
  },
  {
    icao: "EFHK",
    iata: "HEL",
    name: "Vantaa",
    city: "Vantaa",
    country: "FI",
    latitude: 60.317222,
    longitude: 24.963333,
    frequencies: ["127.000"],
    region: "Finland",
    volmetName: "Helsinki VOLMET",
    atis: "135.07",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EFTP",
    iata: "TMP",
    name: "Pirkkala",
    city: "Pirkkala",
    country: "FI",
    latitude: 61.415278,
    longitude: 23.587778,
    frequencies: ["127.000"],
    region: "Finland",
    volmetName: "Helsinki VOLMET",
    atis: "133.55",
    isActive: true,
  },
  {
    icao: "EGAA",
    iata: "BFS",
    name: "Aldergrove",
    city: "Aldergrove",
    country: "GB",
    latitude: 54.6575,
    longitude: -6.215833,
    frequencies: ["128.175"],
    region: "United Kingdom",
    volmetName: "London VOLMET North",
    atis: "126.13",
    isActive: true,
  },
  {
    icao: "EGAC",
    iata: "BHD",
    name: "Belfast City",
    city: "Belfast City",
    country: "GB",
    latitude: 54.618056,
    longitude: -5.8725,
    frequencies: ["128.175"],
    region: "United Kingdom",
    volmetName: "London VOLMET North",
    atis: "124.58",
    isActive: true,
  },
  {
    icao: "EGBB",
    iata: "BHX",
    name: "Birmingham",
    city: "Birmingham",
    country: "GB",
    latitude: 52.453889,
    longitude: -1.748056,
    frequencies: ["135.375"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "136.03",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EGBJ",
    iata: "GLO",
    name: "Gloucestershire",
    city: "Gloucestershire",
    country: "GB",
    latitude: 51.894167,
    longitude: -2.167222,
    frequencies: ["135.375"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "127.48",
    isActive: true,
  },
  {
    icao: "EGCC",
    iata: "MAN",
    name: "Manchester",
    city: "Manchester",
    country: "GB",
    latitude: 53.353611,
    longitude: -2.275,
    frequencies: ["128.175"],
    region: "United Kingdom",
    volmetName: "London VOLMET North",
    atis: "121.98",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EGGW",
    iata: "LTN",
    name: "Luton",
    city: "Luton",
    country: "GB",
    latitude: 51.874722,
    longitude: -0.368333,
    frequencies: ["135.375"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "120.58",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EGHI",
    iata: "SOU",
    name: "Southampton",
    city: "Southampton",
    country: "GB",
    latitude: 50.950278,
    longitude: -1.356667,
    frequencies: ["135.375"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "130.88",
    isActive: true,
  },
  {
    icao: "EGKK",
    iata: "LGW",
    name: "Gatwick",
    city: "Gatwick",
    country: "GB",
    latitude: 51.148056,
    longitude: -0.190278,
    frequencies: ["135.375"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "136.52",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EGLC",
    iata: "LCY",
    name: "London City",
    city: "London City",
    country: "GB",
    latitude: 51.505278,
    longitude: 0.055278,
    frequencies: ["135.375"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "136.355",
    isActive: true,
  },
  {
    icao: "EGLL",
    iata: "LHR",
    name: "Heathrow",
    city: "Heathrow",
    country: "GB",
    latitude: 51.4775,
    longitude: -0.461389,
    frequencies: ["135.375"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "113.75",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EGNM",
    iata: "LBA",
    name: "Leeds Bradford",
    city: "Leeds Bradford",
    country: "GB",
    latitude: 53.866111,
    longitude: -1.660833,
    frequencies: ["128.175"],
    region: "United Kingdom",
    volmetName: "London VOLMET North",
    atis: "118.03",
    isActive: true,
  },
  {
    icao: "EGNT",
    iata: "NCL",
    name: "Newcastle",
    city: "Newcastle",
    country: "GB",
    latitude: 55.038056,
    longitude: -1.689722,
    frequencies: ["128.175"],
    region: "United Kingdom",
    volmetName: "London VOLMET North",
    atis: "118.38",
    isActive: true,
  },
  {
    icao: "EGNX",
    iata: "EMA",
    name: "East Midlands",
    city: "East Midlands",
    country: "GB",
    latitude: 52.831111,
    longitude: -1.327778,
    frequencies: ["128.175"],
    region: "United Kingdom",
    volmetName: "London VOLMET North",
    atis: "122.68",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EGPD",
    iata: "ABZ",
    name: "Dyce",
    city: "Dyce",
    country: "GB",
    latitude: 57.2025,
    longitude: -2.198056,
    frequencies: ["128.175"],
    region: "United Kingdom",
    volmetName: "London VOLMET North",
    atis: "114.3",
    isActive: true,
  },
  {
    icao: "EGPF",
    iata: "GLA",
    name: "Glasgow",
    city: "Glasgow",
    country: "GB",
    latitude: 55.871944,
    longitude: -4.433056,
    frequencies: ["128.175"],
    region: "United Kingdom",
    volmetName: "London VOLMET North",
    atis: "129.58",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EGPH",
    iata: "EDI",
    name: "Edinburgh",
    city: "Edinburgh",
    country: "GB",
    latitude: 55.95,
    longitude: -3.3725,
    frequencies: ["128.175"],
    region: "United Kingdom",
    volmetName: "London VOLMET North",
    atis: "131.355",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EGSH",
    iata: "NWI",
    name: "Norwich",
    city: "Norwich",
    country: "GB",
    latitude: 52.675833,
    longitude: 1.282778,
    frequencies: ["135.375"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "128.63",
    isActive: true,
  },
  {
    icao: "EGSS",
    iata: "STN",
    name: "Stansted",
    city: "Stansted",
    country: "GB",
    latitude: 51.885,
    longitude: 0.235,
    frequencies: ["135.375"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "114.55",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EGTE",
    iata: "EXT",
    name: "Exeter",
    city: "Exeter",
    country: "GB",
    latitude: 50.734167,
    longitude: -3.413889,
    frequencies: ["135.375"],
    region: "United Kingdom",
    volmetName: "London VOLMET Main",
    atis: "119.33",
    isActive: true,
  },
  {
    icao: "EHAM",
    iata: "AMS",
    name: "Schiphol",
    city: "Schiphol",
    country: "NL",
    latitude: 52.308056,
    longitude: 4.764167,
    frequencies: ["127.000"],
    region: "Netherlands",
    volmetName: "Amsterdam VOLMET",
    atis: "122.205",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EHEH",
    iata: "EIN",
    name: "Eindhoven",
    city: "Eindhoven",
    country: "NL",
    latitude: 51.45,
    longitude: 5.374444,
    frequencies: ["127.000"],
    region: "Netherlands",
    volmetName: "Amsterdam VOLMET",
    atis: "126.03",
    isActive: true,
  },
  {
    icao: "EHRD",
    iata: "RTM",
    name: "Rotterdam",
    city: "Rotterdam",
    country: "NL",
    latitude: 51.956944,
    longitude: 4.437222,
    frequencies: ["127.000"],
    region: "Netherlands",
    volmetName: "Amsterdam VOLMET",
    atis: "128.565",
    isActive: true,
  },
  {
    icao: "EICK",
    iata: "ORK",
    name: "Cork Intl",
    city: "Cork Intl",
    country: "IE",
    latitude: 51.841389,
    longitude: -8.491111,
    frequencies: ["135.675"],
    region: "Ireland",
    volmetName: "Shannon VOLMET",
    atis: "120.92",
    isActive: true,
  },
  {
    icao: "EIDL",
    iata: "CFN",
    name: "Donegal",
    city: "Donegal",
    country: "IE",
    latitude: 55.044167,
    longitude: -8.341111,
    frequencies: ["135.675"],
    region: "Ireland",
    volmetName: "Shannon VOLMET",
    atis: "129.93",
    isActive: true,
  },
  {
    icao: "EIDW",
    iata: "DUB",
    name: "Dublin Intl",
    city: "Dublin Intl",
    country: "IE",
    latitude: 53.421389,
    longitude: -6.27,
    frequencies: ["135.675"],
    region: "Ireland",
    volmetName: "Shannon VOLMET",
    atis: "124.53",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EINN",
    iata: "SNN",
    name: "Shannon Intl",
    city: "Shannon Intl",
    country: "IE",
    latitude: 52.701978,
    longitude: -8.924817,
    frequencies: ["135.675"],
    region: "Ireland",
    volmetName: "Shannon VOLMET",
    atis: "130.955",
    isActive: true,
  },
  {
    icao: "EKBI",
    iata: "BLL",
    name: "Billund",
    city: "Billund",
    country: "DK",
    latitude: 55.740322,
    longitude: 9.151778,
    frequencies: ["127.000"],
    region: "Denmark",
    volmetName: "Amsterdam VOLMET",
    atis: "118.78",
    isActive: true,
  },
  {
    icao: "EKCH",
    iata: "CPH",
    name: "Kastrup",
    city: "Kastrup",
    country: "DK",
    latitude: 55.617917,
    longitude: 12.655972,
    frequencies: ["127.000"],
    region: "Denmark",
    volmetName: "Amsterdam VOLMET",
    atis: "122.755",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "ELLX",
    iata: "LUX",
    name: "Luxembourg",
    city: "Luxembourg",
    country: "LU",
    latitude: 49.623333,
    longitude: 6.204444,
    frequencies: ["127.000"],
    region: "Luxembourg",
    volmetName: "Amsterdam VOLMET",
    atis: "134.755",
    isActive: true,
  },
  {
    icao: "ENBR",
    iata: "BGO",
    name: "Flesland",
    city: "Flesland",
    country: "NO",
    latitude: 60.293611,
    longitude: 5.218056,
    frequencies: ["127.000"],
    region: "Norway",
    volmetName: "Stockholm VOLMET",
    atis: "125.255",
    isActive: true,
  },
  {
    icao: "ENGM",
    iata: "OSL",
    name: "Gardermoen",
    city: "Gardermoen",
    country: "NO",
    latitude: 60.202778,
    longitude: 11.083889,
    frequencies: ["127.000"],
    region: "Norway",
    volmetName: "Stockholm VOLMET",
    atis: "126.13",
    isActive: true,
  },
  {
    icao: "EPBG",
    name: "EPBG",
    city: "EPBG",
    country: "PL",
    frequencies: ["126.425"],
    region: "Poland",
    volmetName: "Warsaw VOLMET",
    isActive: true,
  },
  {
    icao: "EPBY",
    iata: "BZG",
    name: "Bydgoszcz",
    city: "Bydgoszcz",
    country: "PL",
    latitude: 53.096667,
    longitude: 17.977778,
    frequencies: ["126.425"],
    region: "Poland",
    volmetName: "Warsaw VOLMET",
    atis: "129.33",
    isActive: true,
  },
  {
    icao: "EPGD",
    iata: "GDN",
    name: "Lech Walesa",
    city: "Lech Walesa",
    country: "PL",
    latitude: 54.3775,
    longitude: 18.466111,
    frequencies: ["126.425"],
    region: "Poland",
    volmetName: "Warsaw VOLMET",
    atis: "129.63",
    isActive: true,
  },
  {
    icao: "EPKK",
    iata: "KRK",
    name: "Balice",
    city: "Balice",
    country: "PL",
    latitude: 50.077778,
    longitude: 19.784722,
    frequencies: ["126.425"],
    region: "Poland",
    volmetName: "Warsaw VOLMET",
    atis: "112.8",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EPKT",
    iata: "KTW",
    name: "Pyrzowice",
    city: "Pyrzowice",
    country: "PL",
    latitude: 50.474167,
    longitude: 19.08,
    frequencies: ["126.425"],
    region: "Poland",
    volmetName: "Warsaw VOLMET",
    atis: "120.23",
    isActive: true,
  },
  {
    icao: "EPLL",
    iata: "LCJ",
    name: "Lodz",
    city: "Lodz",
    country: "PL",
    latitude: 51.721944,
    longitude: 19.398056,
    frequencies: ["126.425"],
    region: "Poland",
    volmetName: "Warsaw VOLMET",
    atis: "135.68",
    isActive: true,
  },
  {
    icao: "EPPO",
    iata: "POZ",
    name: "Lawica",
    city: "Lawica",
    country: "PL",
    latitude: 52.421111,
    longitude: 16.826389,
    frequencies: ["126.425"],
    region: "Poland",
    volmetName: "Warsaw VOLMET",
    atis: "124.705",
    isActive: true,
  },
  {
    icao: "EPRZ",
    iata: "RZE",
    name: "Jasionka",
    city: "Jasionka",
    country: "PL",
    latitude: 50.11,
    longitude: 22.018889,
    frequencies: ["126.425"],
    region: "Poland",
    volmetName: "Warsaw VOLMET",
    atis: "124.955",
    isActive: true,
  },
  {
    icao: "EPSC",
    iata: "SZZ",
    name: "Goleniow",
    city: "Goleniow",
    country: "PL",
    latitude: 53.584722,
    longitude: 14.902222,
    frequencies: ["126.425"],
    region: "Poland",
    volmetName: "Warsaw VOLMET",
    atis: "132.13",
    isActive: true,
  },
  {
    icao: "EPWA",
    iata: "WAW",
    name: "Chopin",
    city: "Chopin",
    country: "PL",
    latitude: 52.165833,
    longitude: 20.967222,
    frequencies: ["126.425"],
    region: "Poland",
    volmetName: "Warsaw VOLMET",
    atis: "120.455",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EPWR",
    iata: "WRO",
    name: "Strachowice",
    city: "Strachowice",
    country: "PL",
    latitude: 51.102778,
    longitude: 16.885833,
    frequencies: ["126.425"],
    region: "Poland",
    volmetName: "Warsaw VOLMET",
    atis: "124.33",
    isActive: true,
  },
  {
    icao: "ESGG",
    iata: "GOT",
    name: "Landvetter",
    city: "Landvetter",
    country: "SE",
    latitude: 57.66,
    longitude: 12.291111,
    frequencies: ["127.000"],
    region: "Sweden",
    volmetName: "Stockholm VOLMET",
    atis: "114.6",
    isActive: true,
  },
  {
    icao: "ESMS",
    iata: "MMX",
    name: "Malmo",
    city: "Malmo",
    country: "SE",
    latitude: 55.548333,
    longitude: 13.353333,
    frequencies: ["127.000"],
    region: "Sweden",
    volmetName: "Stockholm VOLMET",
    atis: "129.28",
    isActive: true,
  },
  {
    icao: "ESSA",
    iata: "ARN",
    name: "Arlanda",
    city: "Arlanda",
    country: "SE",
    latitude: 59.651944,
    longitude: 17.918611,
    frequencies: ["127.000"],
    region: "Sweden",
    volmetName: "Stockholm VOLMET",
    atis: "119.005",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "EVRA",
    iata: "RIX",
    name: "Riga",
    city: "Riga",
    country: "LV",
    latitude: 56.923611,
    longitude: 23.971111,
    frequencies: ["126.425"],
    region: "Latvia",
    volmetName: "Helsinki VOLMET",
    atis: "120.17",
    isActive: true,
  },
  {
    icao: "EYVI",
    iata: "VNO",
    name: "Vilnius Intl",
    city: "Vilnius Intl",
    country: "LT",
    latitude: 54.636944,
    longitude: 25.287778,
    frequencies: ["126.425"],
    region: "Lithuania",
    volmetName: "Helsinki VOLMET",
    atis: "125.805",
    isActive: true,
  },
  {
    icao: "GCFV",
    iata: "FUE",
    name: "Fuerteventura",
    city: "Fuerteventura",
    country: "ES",
    latitude: 28.452778,
    longitude: -13.863889,
    frequencies: ["127.675"],
    region: "Spain - Canary Islands",
    volmetName: "Canarias VOLMET",
    atis: "118.65",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "GCLA",
    iata: "SPC",
    name: "La Palma",
    city: "La Palma",
    country: "ES",
    latitude: 28.626667,
    longitude: -17.755556,
    frequencies: ["127.675"],
    region: "Spain - Canary Islands",
    volmetName: "Canarias VOLMET",
    atis: "118.25",
    isActive: true,
  },
  {
    icao: "GCLP",
    iata: "LPA",
    name: "Gran Canaria",
    city: "Gran Canaria",
    country: "ES",
    latitude: 27.931944,
    longitude: -15.386667,
    frequencies: ["127.675"],
    region: "Spain - Canary Islands",
    volmetName: "Canarias VOLMET",
    atis: "118.6",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "GCRR",
    iata: "ACE",
    name: "Cesar Manrique Lanzarote",
    city: "Cesar Manrique Lanzarote",
    country: "ES",
    latitude: 28.945556,
    longitude: -13.605278,
    frequencies: ["127.675"],
    region: "Spain - Canary Islands",
    volmetName: "Canarias VOLMET",
    atis: "118.62",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "GCTS",
    iata: "TFS",
    name: "Tenerife South",
    city: "Tenerife South",
    country: "ES",
    latitude: 28.044444,
    longitude: -16.5725,
    frequencies: ["127.675"],
    region: "Spain - Canary Islands",
    volmetName: "Canarias VOLMET",
    atis: "118.67",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "GCXO",
    iata: "TFN",
    name: "Ciudad De La Laguna",
    city: "Ciudad De La Laguna",
    country: "ES",
    latitude: 28.482778,
    longitude: -16.341667,
    frequencies: ["127.675"],
    region: "Spain - Canary Islands",
    volmetName: "Canarias VOLMET",
    atis: "118.57",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "GMAD",
    iata: "AGA",
    name: "Al Massira Intl",
    city: "Al Massira Intl",
    country: "MA",
    latitude: 30.3225,
    longitude: -9.411389,
    frequencies: ["127.675"],
    region: "Morocco",
    volmetName: "Casablanca VOLMET",
    atis: "127.75",
    isActive: true,
  },
  {
    icao: "GMFN",
    name: "GMFN",
    city: "GMFN",
    country: "MA",
    frequencies: ["127.675"],
    region: "Morocco",
    volmetName: "Casablanca VOLMET",
    isActive: true,
  },
  {
    icao: "GMME",
    iata: "RBA",
    name: "Sale Intl",
    city: "Sale Intl",
    country: "MA",
    latitude: 34.051389,
    longitude: -6.751667,
    frequencies: ["127.675"],
    region: "Morocco",
    volmetName: "Casablanca VOLMET",
    atis: "127.7",
    isActive: true,
  },
  {
    icao: "GMMN",
    iata: "CMN",
    name: "Mohammed V Intl",
    city: "Mohammed V Intl",
    country: "MA",
    latitude: 33.364167,
    longitude: -7.581667,
    frequencies: ["127.675"],
    region: "Morocco",
    volmetName: "Casablanca VOLMET",
    atis: "126.3",
    isActive: true,
  },
  {
    icao: "GMMX",
    iata: "RAK",
    name: "Menara Intl",
    city: "Menara Intl",
    country: "MA",
    latitude: 31.608611,
    longitude: -8.040833,
    frequencies: ["127.675"],
    region: "Morocco",
    volmetName: "Casablanca VOLMET",
    atis: "121.95",
    isActive: true,
  },
  {
    icao: "GMMZ",
    iata: "OZZ",
    name: "Ouarzazate Intl",
    city: "Ouarzazate Intl",
    country: "MA",
    latitude: 30.937222,
    longitude: -6.906111,
    frequencies: ["127.675"],
    region: "Morocco",
    volmetName: "Casablanca VOLMET",
    atis: "118.8",
    isActive: true,
  },
  {
    icao: "GMTT",
    iata: "TNG",
    name: "Ibn Batouta Intl",
    city: "Ibn Batouta Intl",
    country: "MA",
    latitude: 35.731667,
    longitude: -5.921111,
    frequencies: ["127.675"],
    region: "Morocco",
    volmetName: "Casablanca VOLMET",
    atis: "123.7",
    isActive: true,
  },
  {
    icao: "HECA",
    iata: "CAI",
    name: "Cairo Intl",
    city: "Cairo Intl",
    country: "EG",
    latitude: 30.111389,
    longitude: 31.413889,
    frequencies: ["126.450"],
    region: "Egypt",
    volmetName: "Cairo VOLMET",
    atis: "122.6",
    isActive: true,
  },
  {
    icao: "HEGN",
    iata: "HRG",
    name: "Hurghada Intl",
    city: "Hurghada Intl",
    country: "EG",
    latitude: 27.178611,
    longitude: 33.800833,
    frequencies: ["126.450"],
    region: "Egypt",
    volmetName: "Cairo VOLMET",
    atis: "120.45",
    isActive: true,
  },
  {
    icao: "HESH",
    iata: "SSH",
    name: "Sharm El Sheikh Intl",
    city: "Sharm El Sheikh Intl",
    country: "EG",
    latitude: 27.978611,
    longitude: 34.393333,
    frequencies: ["126.450"],
    region: "Egypt",
    volmetName: "Cairo VOLMET",
    atis: "126.22",
    isActive: true,
  },
  {
    icao: "LATI",
    iata: "TIA",
    name: "Tirana",
    city: "Tirana",
    country: "XX",
    latitude: 41.414722,
    longitude: 19.720556,
    frequencies: ["126.425"],
    region: "Albania",
    volmetName: "Rome VOLMET",
    atis: "132.27",
    isActive: true,
  },
  {
    icao: "LBBG",
    iata: "BOJ",
    name: "Burgas",
    city: "Burgas",
    country: "BG",
    latitude: 42.570278,
    longitude: 27.515278,
    frequencies: ["126.450"],
    region: "Bulgaria",
    volmetName: "Sofia VOLMET",
    atis: "128.88",
    isActive: true,
  },
  {
    icao: "LBPD",
    iata: "PDV",
    name: "Plovdiv",
    city: "Plovdiv",
    country: "BG",
    latitude: 42.067778,
    longitude: 24.850833,
    frequencies: ["126.450"],
    region: "Bulgaria",
    volmetName: "Sofia VOLMET",
    atis: "129.215",
    isActive: true,
  },
  {
    icao: "LBSF",
    iata: "SOF",
    name: "Vasil Levski Sofia",
    city: "Vasil Levski Sofia",
    country: "BG",
    latitude: 42.695,
    longitude: 23.408333,
    frequencies: ["126.450"],
    region: "Bulgaria",
    volmetName: "Sofia VOLMET",
    atis: "126.68",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "LBWN",
    iata: "VAR",
    name: "Varna",
    city: "Varna",
    country: "BG",
    latitude: 43.231944,
    longitude: 27.825278,
    frequencies: ["126.450"],
    region: "Bulgaria",
    volmetName: "Sofia VOLMET",
    atis: "126.88",
    isActive: true,
  },
  {
    icao: "LCLK",
    iata: "LCA",
    name: "Larnaca Intl",
    city: "Larnaca Intl",
    country: "CY",
    latitude: 34.878889,
    longitude: 33.630278,
    frequencies: ["126.450"],
    region: "Cyprus",
    volmetName: "Nicosia VOLMET",
    atis: "126.55",
    isActive: true,
  },
  {
    icao: "LCPH",
    iata: "PFO",
    name: "Pafos Intl",
    city: "Pafos Intl",
    country: "CY",
    latitude: 34.718078,
    longitude: 32.485072,
    frequencies: ["126.450"],
    region: "Cyprus",
    volmetName: "Nicosia VOLMET",
    atis: "127.32",
    isActive: true,
  },
  {
    icao: "LDDU",
    iata: "DBV",
    name: "Rudjer Boskovic",
    city: "Rudjer Boskovic",
    country: "HR",
    latitude: 42.561353,
    longitude: 18.268244,
    frequencies: ["126.425"],
    region: "Croatia",
    volmetName: "Zagreb VOLMET",
    atis: "118.42",
    isActive: true,
  },
  {
    icao: "LDSP",
    iata: "SPU",
    name: "St Jerome",
    city: "St Jerome",
    country: "HR",
    latitude: 43.538944,
    longitude: 16.297964,
    frequencies: ["126.425"],
    region: "Croatia",
    volmetName: "Zagreb VOLMET",
    atis: "125.3",
    isActive: true,
  },
  {
    icao: "LDZA",
    iata: "ZAG",
    name: "Franjo Tudjman",
    city: "Franjo Tudjman",
    country: "HR",
    latitude: 45.742931,
    longitude: 16.068778,
    frequencies: ["126.425"],
    region: "Croatia",
    volmetName: "Zagreb VOLMET",
    atis: "124.57",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "LDZD",
    iata: "ZAD",
    name: "Zemunik",
    city: "Zemunik",
    country: "HR",
    latitude: 44.108269,
    longitude: 15.346697,
    frequencies: ["126.425"],
    region: "Croatia",
    volmetName: "Zagreb VOLMET",
    atis: "126.685",
    isActive: true,
  },
  {
    icao: "LEAL",
    iata: "ALC",
    name: "Alicante Elche Miguel Hernande",
    city: "Alicante Elche Miguel Hernande",
    country: "ES",
    latitude: 38.282222,
    longitude: -0.558056,
    frequencies: ["127.675"],
    region: "Spain",
    volmetName: "Madrid VOLMET",
    atis: "120.08",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "LEAM",
    iata: "LEI",
    name: "Almeria",
    city: "Almeria",
    country: "ES",
    latitude: 36.843889,
    longitude: -2.37,
    frequencies: ["127.675"],
    region: "Spain",
    volmetName: "Madrid VOLMET",
    atis: "119.055",
    isActive: true,
  },
  {
    icao: "LEBB",
    iata: "BIO",
    name: "Bilbao",
    city: "Bilbao",
    country: "ES",
    latitude: 43.301111,
    longitude: -2.910556,
    frequencies: ["127.675"],
    region: "Spain",
    volmetName: "Madrid VOLMET",
    atis: "118.83",
    isActive: true,
  },
  {
    icao: "LEBL",
    iata: "BCN",
    name: "Josep Tarradellas El Prat",
    city: "Josep Tarradellas El Prat",
    country: "ES",
    latitude: 41.296944,
    longitude: 2.078333,
    frequencies: ["127.675"],
    region: "Spain",
    volmetName: "Madrid VOLMET",
    atis: "118.655",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "LEGO",
    name: "LEGO",
    city: "LEGO",
    country: "ES",
    frequencies: ["127.675"],
    region: "Spain",
    volmetName: "Madrid VOLMET",
    isActive: true,
  },
  {
    icao: "LEGR",
    iata: "GRX",
    name: "Federico Garcia Lorca",
    city: "Federico Garcia Lorca",
    country: "ES",
    latitude: 37.188611,
    longitude: -3.777222,
    frequencies: ["127.675"],
    region: "Spain",
    volmetName: "Madrid VOLMET",
    atis: "120.63",
    isActive: true,
  },
  {
    icao: "LEIB",
    iata: "IBZ",
    name: "Ibiza",
    city: "Ibiza",
    country: "ES",
    latitude: 38.872778,
    longitude: 1.373056,
    frequencies: ["127.675"],
    region: "Spain - Balearics",
    volmetName: "Madrid VOLMET",
    atis: "119.805",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "LEMD",
    iata: "MAD",
    name: "Adolfo Suarez Madrid Barajas",
    city: "Adolfo Suarez Madrid Barajas",
    country: "ES",
    latitude: 40.472222,
    longitude: -3.560833,
    frequencies: ["127.675"],
    region: "Spain",
    volmetName: "Madrid VOLMET",
    atis: "118.255",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "LEMG",
    iata: "AGP",
    name: "Costa Del Sol",
    city: "Costa Del Sol",
    country: "ES",
    latitude: 36.675,
    longitude: -4.499167,
    frequencies: ["127.675"],
    region: "Spain",
    volmetName: "Madrid VOLMET",
    atis: "120.38",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "LEMH",
    iata: "MAH",
    name: "Menorca",
    city: "Menorca",
    country: "ES",
    latitude: 39.8625,
    longitude: 4.218611,
    frequencies: ["127.675"],
    region: "Spain - Balearics",
    volmetName: "Madrid VOLMET",
    atis: "129.155",
    isActive: true,
  },
  {
    icao: "LEPA",
    iata: "PMI",
    name: "Palma De Mallorca",
    city: "Palma De Mallorca",
    country: "ES",
    latitude: 39.551667,
    longitude: 2.738889,
    frequencies: ["127.675"],
    region: "Spain - Balearics",
    volmetName: "Madrid VOLMET",
    atis: "119.255",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "LEVC",
    iata: "VLC",
    name: "Valencia",
    city: "Valencia",
    country: "ES",
    latitude: 39.489444,
    longitude: -0.481667,
    frequencies: ["127.675"],
    region: "Spain",
    volmetName: "Madrid VOLMET",
    atis: "121.08",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "LEVT",
    iata: "VIT",
    name: "Vitoria",
    city: "Vitoria",
    country: "ES",
    latitude: 42.882778,
    longitude: -2.724444,
    frequencies: ["127.675"],
    region: "Spain",
    volmetName: "Madrid VOLMET",
    atis: "119.355",
    isActive: true,
  },
  {
    icao: "LEZL",
    iata: "SVQ",
    name: "Seville",
    city: "Seville",
    country: "ES",
    latitude: 37.418056,
    longitude: -5.898889,
    frequencies: ["127.675"],
    region: "Spain",
    volmetName: "Madrid VOLMET",
    atis: "118.18",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "LFBD",
    iata: "BOD",
    name: "Merignac",
    city: "Merignac",
    country: "FR",
    latitude: 44.828611,
    longitude: -0.715278,
    frequencies: ["126.450"],
    region: "France",
    volmetName: "Paris VOLMET",
    atis: "131.155",
    isActive: true,
  },
  {
    icao: "LFBT",
    iata: "LDE",
    name: "Lourdes Pyrenees",
    city: "Lourdes Pyrenees",
    country: "FR",
    latitude: 43.185556,
    longitude: -0.002778,
    frequencies: ["126.450"],
    region: "France",
    volmetName: "Paris VOLMET",
    atis: "125.955",
    isActive: true,
  },
  {
    icao: "LFBZ",
    iata: "BIQ",
    name: "Pays Basque",
    city: "Pays Basque",
    country: "FR",
    latitude: 43.468333,
    longitude: -1.531111,
    frequencies: ["126.450"],
    region: "France",
    volmetName: "Paris VOLMET",
    atis: "128.23",
    isActive: true,
  },
  {
    icao: "LFKB",
    iata: "BIA",
    name: "Poretta",
    city: "Poretta",
    country: "FR",
    latitude: 42.55,
    longitude: 9.484722,
    frequencies: ["126.450"],
    region: "France - Corsica",
    volmetName: "Paris VOLMET",
    atis: "125.93",
    isActive: true,
  },
  {
    icao: "LFKJ",
    iata: "AJA",
    name: "Napoleon Bonaparte",
    city: "Napoleon Bonaparte",
    country: "FR",
    latitude: 41.923889,
    longitude: 8.8025,
    frequencies: ["126.450"],
    region: "France - Corsica",
    volmetName: "Paris VOLMET",
    atis: "126.93",
    isActive: true,
  },
  {
    icao: "LFLB",
    iata: "CMF",
    name: "Aix Les Bains",
    city: "Aix Les Bains",
    country: "FR",
    latitude: 45.639167,
    longitude: 5.88,
    frequencies: ["126.450"],
    region: "France",
    volmetName: "Paris VOLMET",
    atis: "127.1",
    isActive: true,
  },
  {
    icao: "LFML",
    iata: "MRS",
    name: "Marseille Provence",
    city: "Marseille Provence",
    country: "FR",
    latitude: 43.436667,
    longitude: 5.215,
    frequencies: ["126.450"],
    region: "France",
    volmetName: "Paris VOLMET",
    atis: "125.355",
    isActive: true,
  },
  {
    icao: "LFMN",
    iata: "NCE",
    name: "Nice Cote Dazur",
    city: "Nice Cote Dazur",
    country: "FR",
    latitude: 43.665278,
    longitude: 7.215,
    frequencies: ["126.450"],
    region: "France",
    volmetName: "Paris VOLMET",
    atis: "129.605",
    isActive: true,
  },
  {
    icao: "LFMT",
    iata: "MPL",
    name: "Montpellier Mediterranee",
    city: "Montpellier Mediterranee",
    country: "FR",
    latitude: 43.583333,
    longitude: 3.961389,
    frequencies: ["126.450"],
    region: "France",
    volmetName: "Paris VOLMET",
    atis: "124.13",
    isActive: true,
  },
  {
    icao: "LFPG",
    iata: "CDG",
    name: "Charles De Gaulle",
    city: "Charles De Gaulle",
    country: "FR",
    latitude: 49.009722,
    longitude: 2.547778,
    frequencies: ["126.450"],
    region: "France",
    volmetName: "Paris VOLMET",
    atis: "127.13",
    handlingFrequency: "131.425",
    isActive: true,
  },
  {
    icao: "LFPO",
    iata: "ORY",
    name: "Orly",
    city: "Orly",
    country: "FR",
    latitude: 48.723333,
    longitude: 2.379444,
    frequencies: ["126.450"],
    region: "France",
    volmetName: "Paris VOLMET",
    atis: "126.505",
    handlingFrequency: "131.425",
    isActive: true,
  },
  {
    icao: "LFRB",
    iata: "BES",
    name: "Bretagne",
    city: "Bretagne",
    country: "FR",
    latitude: 48.447222,
    longitude: -4.421667,
    frequencies: ["126.450"],
    region: "France",
    volmetName: "Paris VOLMET",
    atis: "129.355",
    isActive: true,
  },
  {
    icao: "LFRN",
    iata: "RNS",
    name: "St Jacques",
    city: "St Jacques",
    country: "FR",
    latitude: 48.071944,
    longitude: -1.732222,
    frequencies: ["126.450"],
    region: "France",
    volmetName: "Paris VOLMET",
    atis: "136.405",
    isActive: true,
  },
  {
    icao: "LFRO",
    iata: "LAI",
    name: "Lannion",
    city: "Lannion",
    country: "FR",
    latitude: 48.754444,
    longitude: -3.471944,
    frequencies: ["126.450"],
    region: "France",
    volmetName: "Paris VOLMET",
    isActive: true,
  },
  {
    icao: "LFRS",
    iata: "NTE",
    name: "Nantes Atlantique",
    city: "Nantes Atlantique",
    country: "FR",
    latitude: 47.156944,
    longitude: -1.607778,
    frequencies: ["126.450"],
    region: "France",
    volmetName: "Paris VOLMET",
    atis: "126.93",
    isActive: true,
  },
  {
    icao: "LFST",
    iata: "SXB",
    name: "Entzheim",
    city: "Entzheim",
    country: "FR",
    latitude: 48.541944,
    longitude: 7.634444,
    frequencies: ["126.450"],
    region: "France",
    volmetName: "Paris VOLMET",
    atis: "126.93",
    isActive: true,
  },
  {
    icao: "LGAV",
    iata: "ATH",
    name: "Eleftherios Venizelos Intl",
    city: "Eleftherios Venizelos Intl",
    country: "XX",
    latitude: 37.9367,
    longitude: 23.9445,
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    atis: "136.12",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "LGHI",
    iata: "JKH",
    name: "Omiros",
    city: "Omiros",
    country: "XX",
    latitude: 38.343333,
    longitude: 26.140556,
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    isActive: true,
  },
  {
    icao: "LGIR",
    iata: "HER",
    name: "Nikos Kazantzakis",
    city: "Nikos Kazantzakis",
    country: "XX",
    latitude: 35.339722,
    longitude: 25.180278,
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    atis: "127.555",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "LGKF",
    iata: "EFL",
    name: "Anna Pollatou",
    city: "Anna Pollatou",
    country: "XX",
    latitude: 38.12,
    longitude: 20.500556,
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    atis: "126.455",
    isActive: true,
  },
  {
    icao: "LGKO",
    iata: "KGS",
    name: "Ippokratis",
    city: "Ippokratis",
    country: "XX",
    latitude: 36.794722,
    longitude: 27.091111,
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    atis: "126.955",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "LGKP",
    iata: "AOK",
    name: "Karpathos",
    city: "Karpathos",
    country: "XX",
    latitude: 35.421111,
    longitude: 27.145833,
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    isActive: true,
  },
  {
    icao: "LGKR",
    iata: "CFU",
    name: "Ioannis Kapodistrias",
    city: "Ioannis Kapodistrias",
    country: "XX",
    latitude: 39.601944,
    longitude: 19.912222,
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    atis: "126.355",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "LGLM",
    iata: "LXS",
    name: "Ifaistos",
    city: "Ifaistos",
    country: "XX",
    latitude: 39.917222,
    longitude: 25.236389,
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    isActive: true,
  },
  {
    icao: "LGMK",
    iata: "JMK",
    name: "Mikonos",
    city: "Mikonos",
    country: "XX",
    latitude: 37.437222,
    longitude: 25.347222,
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    atis: "128.855",
    isActive: true,
  },
  {
    icao: "LGMT",
    iata: "MJT",
    name: "Odysseas Elytis",
    city: "Odysseas Elytis",
    country: "XX",
    latitude: 39.057778,
    longitude: 26.598611,
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    isActive: true,
  },
  {
    icao: "LGPL",
    iata: "JTY",
    name: "Astypalaia",
    city: "Astypalaia",
    country: "XX",
    latitude: 36.58,
    longitude: 26.375278,
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    isActive: true,
  },
  {
    icao: "LGPZ",
    iata: "PVK",
    name: "Aktion",
    city: "Aktion",
    country: "XX",
    latitude: 38.925556,
    longitude: 20.765,
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    isActive: true,
  },
  {
    icao: "LGRP",
    iata: "RHO",
    name: "Diagoras",
    city: "Diagoras",
    country: "XX",
    latitude: 36.405278,
    longitude: 28.086111,
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    atis: "126.355",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "LGSK",
    iata: "JSI",
    name: "Alexandros Papadiamandis",
    city: "Alexandros Papadiamandis",
    country: "XX",
    latitude: 39.1775,
    longitude: 23.503611,
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    isActive: true,
  },
  {
    icao: "LGSM",
    iata: "SMI",
    name: "Aristarchos Of Samos",
    city: "Aristarchos Of Samos",
    country: "XX",
    latitude: 37.689167,
    longitude: 26.912222,
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    atis: "127.055",
    isActive: true,
  },
  {
    icao: "LGST",
    iata: "JSH",
    name: "Vitsentzos Kornaros",
    city: "Vitsentzos Kornaros",
    country: "XX",
    latitude: 35.216111,
    longitude: 26.101111,
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    isActive: true,
  },
  {
    icao: "LGTH",
    name: "LGTH",
    city: "LGTH",
    country: "XX",
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    isActive: true,
  },
  {
    icao: "LGZA",
    iata: "ZTH",
    name: "Dionisios Solomos",
    city: "Dionisios Solomos",
    country: "XX",
    latitude: 37.751111,
    longitude: 20.884167,
    frequencies: ["126.450"],
    region: "Greece",
    volmetName: "Athens VOLMET",
    atis: "127.055",
    isActive: true,
  },
  {
    icao: "LHBP",
    iata: "BUD",
    name: "Liszt Ferenc Intl",
    city: "Liszt Ferenc Intl",
    country: "HU",
    latitude: 47.439444,
    longitude: 19.261944,
    frequencies: ["126.425"],
    region: "Hungary",
    volmetName: "Budapest VOLMET",
    atis: "117.3",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "LIBD",
    iata: "BRI",
    name: "Palese",
    city: "Palese",
    country: "IT",
    latitude: 41.138056,
    longitude: 16.765,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "124.05",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LIBF",
    iata: "FOG",
    name: "Gino Lisa",
    city: "Gino Lisa",
    country: "IT",
    latitude: 41.433333,
    longitude: 15.534722,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LIBN",
    iata: "LCC",
    name: "Galatina",
    city: "Galatina",
    country: "IT",
    latitude: 40.238889,
    longitude: 18.133333,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "135.665",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LIBP",
    iata: "PSR",
    name: "Pescara",
    city: "Pescara",
    country: "IT",
    latitude: 42.437222,
    longitude: 14.187222,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LICA",
    iata: "SUF",
    name: "Lamezia Terme",
    city: "Lamezia Terme",
    country: "IT",
    latitude: 38.908333,
    longitude: 16.241667,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "119.93",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LICB",
    iata: "CIY",
    name: "Comiso",
    city: "Comiso",
    country: "IT",
    latitude: 36.995833,
    longitude: 14.608889,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    isActive: true,
  },
  {
    icao: "LICC",
    iata: "CTA",
    name: "Fontanarossa",
    city: "Fontanarossa",
    country: "IT",
    latitude: 37.466667,
    longitude: 15.063889,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "127.67",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LICD",
    iata: "LMP",
    name: "Lampedusa",
    city: "Lampedusa",
    country: "IT",
    latitude: 35.498056,
    longitude: 12.618333,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    isActive: true,
  },
  {
    icao: "LICJ",
    iata: "PMO",
    name: "Punta Raisi",
    city: "Punta Raisi",
    country: "IT",
    latitude: 38.181944,
    longitude: 13.099444,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "123.87",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LICY",
    name: "LICY",
    city: "LICY",
    country: "IT",
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    isActive: true,
  },
  {
    icao: "LICZ",
    iata: "NSY",
    name: "Sigonella",
    city: "Sigonella",
    country: "IT",
    latitude: 37.405892,
    longitude: 14.9239,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    isActive: true,
  },
  {
    icao: "LIEE",
    iata: "CAG",
    name: "Elmas",
    city: "Elmas",
    country: "IT",
    latitude: 39.247222,
    longitude: 9.056111,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "127.055",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LIEO",
    iata: "OLB",
    name: "Costa Smeralda",
    city: "Costa Smeralda",
    country: "IT",
    latitude: 40.898611,
    longitude: 9.517778,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "113.9",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LIMC",
    iata: "MXP",
    name: "Malpensa",
    city: "Malpensa",
    country: "IT",
    latitude: 45.63,
    longitude: 8.723056,
    frequencies: ["126.600"],
    region: "Italy",
    volmetName: "Milano VOLMET",
    atis: "120.02",
    handlingFrequency: "131.975",
    isActive: true,
  },
  {
    icao: "LIME",
    iata: "BGY",
    name: "Orio Al Serio",
    city: "Orio Al Serio",
    country: "IT",
    latitude: 45.668889,
    longitude: 9.700278,
    frequencies: ["126.600"],
    region: "Italy",
    volmetName: "Milano VOLMET",
    atis: "118.54",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LIML",
    iata: "LIN",
    name: "Linate",
    city: "Linate",
    country: "IT",
    latitude: 45.449444,
    longitude: 9.278333,
    frequencies: ["126.600"],
    region: "Italy",
    volmetName: "Milano VOLMET",
    atis: "136.37",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LIPE",
    iata: "BLQ",
    name: "Borgo Panigale",
    city: "Borgo Panigale",
    country: "IT",
    latitude: 44.530833,
    longitude: 11.296944,
    frequencies: ["126.000", "126.600"],
    region: "Italy",
    volmetName: "Roma/Milano VOLMET",
    atis: "134.87",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LIPH",
    iata: "TSF",
    name: "S.angelo",
    city: "S.angelo",
    country: "IT",
    latitude: 45.650833,
    longitude: 12.197778,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LIPU",
    name: "Padova",
    city: "Padova",
    country: "IT",
    latitude: 45.396111,
    longitude: 11.848056,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LIPX",
    iata: "VRN",
    name: "Villafranca",
    city: "Villafranca",
    country: "IT",
    latitude: 45.396389,
    longitude: 10.887778,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "124.13",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LIPZ",
    iata: "VCE",
    name: "Tessera",
    city: "Tessera",
    country: "IT",
    latitude: 45.505278,
    longitude: 12.351944,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "128.655",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LIRA",
    iata: "CIA",
    name: "Ciampino",
    city: "Ciampino",
    country: "IT",
    latitude: 41.799444,
    longitude: 12.597222,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "122.43",
    handlingFrequency: "131.725",
    isActive: true,
  },
  {
    icao: "LIRF",
    iata: "FCO",
    name: "Fiumicino",
    city: "Fiumicino",
    country: "IT",
    latitude: 41.800278,
    longitude: 12.238889,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "121.85",
    handlingFrequency: "131.425",
    isActive: true,
  },
  {
    icao: "LIRJ",
    iata: "EBA",
    name: "Marina Di Campo",
    city: "Marina Di Campo",
    country: "IT",
    latitude: 42.761111,
    longitude: 10.239722,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    isActive: true,
  },
  {
    icao: "LIRN",
    iata: "NAP",
    name: "Capodichino",
    city: "Capodichino",
    country: "IT",
    latitude: 40.884444,
    longitude: 14.290833,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "135.97",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LIRQ",
    iata: "FLR",
    name: "Peretola",
    city: "Peretola",
    country: "IT",
    latitude: 43.808611,
    longitude: 11.202778,
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    atis: "129.35",
    handlingFrequency: "130.475",
    isActive: true,
  },
  {
    icao: "LIRY",
    name: "LIRY",
    city: "LIRY",
    country: "IT",
    frequencies: ["126.000"],
    region: "Italy",
    volmetName: "Roma VOLMET",
    isActive: true,
  },
  {
    icao: "LJLJ",
    iata: "LJU",
    name: "Brnik",
    city: "Brnik",
    country: "SI",
    latitude: 46.224444,
    longitude: 14.456111,
    frequencies: ["126.425"],
    region: "Slovenia",
    volmetName: "Zagreb VOLMET",
    atis: "112.7",
    isActive: true,
  },
  {
    icao: "LKPR",
    iata: "PRG",
    name: "Ruzyne",
    city: "Ruzyne",
    country: "CZ",
    latitude: 50.100833,
    longitude: 14.26,
    frequencies: ["126.425"],
    region: "Czech Republic",
    volmetName: "Frankfurt VOLMET",
    atis: "122.16",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "LLBG",
    iata: "TLV",
    name: "Ben Gurion",
    city: "Ben Gurion",
    country: "IL",
    latitude: 32.009444,
    longitude: 34.885556,
    frequencies: ["126.450"],
    region: "Israel",
    volmetName: "Tel Aviv VOLMET",
    atis: "121.55",
    isActive: true,
  },
  {
    icao: "LMML",
    iata: "MLA",
    name: "Luqa",
    city: "Luqa",
    country: "MT",
    latitude: 35.857542,
    longitude: 14.477439,
    frequencies: ["126.000"],
    region: "Malta",
    volmetName: "Roma VOLMET",
    atis: "127.005",
    handlingFrequency: "131.425",
    isActive: true,
  },
  {
    icao: "LOWI",
    iata: "INN",
    name: "Innsbruck",
    city: "Innsbruck",
    country: "AT",
    latitude: 47.260278,
    longitude: 11.343889,
    frequencies: ["126.425"],
    region: "Austria",
    volmetName: "Frankfurt VOLMET",
    atis: "126.03",
    isActive: true,
  },
  {
    icao: "LOWW",
    iata: "VIE",
    name: "Schwechat",
    city: "Schwechat",
    country: "AT",
    latitude: 48.110278,
    longitude: 16.569722,
    frequencies: ["126.425"],
    region: "Austria",
    volmetName: "Frankfurt VOLMET",
    atis: "121.73",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "LPFR",
    iata: "FAO",
    name: "Gago Coutinho",
    city: "Gago Coutinho",
    country: "PT",
    latitude: 37.014444,
    longitude: -7.965833,
    frequencies: ["127.675"],
    region: "Portugal",
    volmetName: "Madrid VOLMET",
    atis: "121.56",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "LPLA",
    iata: "TER",
    name: "Lajes Ab",
    city: "Lajes Ab",
    country: "PT",
    latitude: 38.761944,
    longitude: -27.090833,
    frequencies: ["127.675"],
    region: "Portugal - Azores",
    volmetName: "Madrid VOLMET",
    atis: "120.3",
    isActive: true,
  },
  {
    icao: "LPMA",
    iata: "FNC",
    name: "Madeira",
    city: "Madeira",
    country: "PT",
    latitude: 32.694167,
    longitude: -16.778056,
    frequencies: ["127.675"],
    region: "Portugal",
    volmetName: "Madrid VOLMET",
    atis: "121.63",
    isActive: true,
  },
  {
    icao: "LPPD",
    iata: "PDL",
    name: "Joao Paulo Ii",
    city: "Joao Paulo Ii",
    country: "PT",
    latitude: 37.741944,
    longitude: -25.697778,
    frequencies: ["127.675"],
    region: "Portugal - Azores",
    volmetName: "Madrid VOLMET",
    atis: "123.9",
    isActive: true,
  },
  {
    icao: "LPPR",
    iata: "OPO",
    name: "Francisco Sa Carneiro",
    city: "Francisco Sa Carneiro",
    country: "PT",
    latitude: 41.235556,
    longitude: -8.678056,
    frequencies: ["127.675"],
    region: "Portugal",
    volmetName: "Madrid VOLMET",
    atis: "121.68",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "LPPT",
    iata: "LIS",
    name: "Humberto Delgado",
    city: "Humberto Delgado",
    country: "PT",
    latitude: 38.774167,
    longitude: -9.134167,
    frequencies: ["127.675"],
    region: "Portugal",
    volmetName: "Madrid VOLMET",
    atis: "121.955",
    handlingFrequency: "131.475",
    isActive: true,
  },
  {
    icao: "LQMO",
    iata: "OMO",
    name: "Mostar",
    city: "Mostar",
    country: "BA",
    latitude: 43.2829,
    longitude: 17.845878,
    frequencies: ["126.425"],
    region: "Bosnia Herzegovina",
    volmetName: "Zagreb VOLMET",
    atis: "126.22",
    isActive: true,
  },
  {
    icao: "LQSA",
    iata: "SJJ",
    name: "Sarajevo",
    city: "Sarajevo",
    country: "BA",
    latitude: 43.824472,
    longitude: 18.331778,
    frequencies: ["126.425"],
    region: "Bosnia Herzegovina",
    volmetName: "Zagreb VOLMET",
    atis: "124.12",
    isActive: true,
  },
  {
    icao: "LRCK",
    iata: "CND",
    name: "Mihail Kogalniceanu Constanta",
    city: "Mihail Kogalniceanu Constanta",
    country: "RO",
    latitude: 44.362222,
    longitude: 28.488333,
    frequencies: ["126.450"],
    region: "Romania",
    volmetName: "Bucharest VOLMET",
    atis: "118.75",
    isActive: true,
  },
  {
    icao: "LRCL",
    iata: "CLJ",
    name: "Avram Iancu",
    city: "Avram Iancu",
    country: "RO",
    latitude: 46.789167,
    longitude: 23.692222,
    frequencies: ["126.450"],
    region: "Romania",
    volmetName: "Bucharest VOLMET",
    atis: "125.52",
    isActive: true,
  },
  {
    icao: "LROP",
    iata: "OTP",
    name: "Henri Coanda",
    city: "Henri Coanda",
    country: "RO",
    latitude: 44.571111,
    longitude: 26.085,
    frequencies: ["126.450"],
    region: "Romania",
    volmetName: "Bucharest VOLMET",
    atis: "118.5",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "LRSB",
    iata: "SBZ",
    name: "Sibiu",
    city: "Sibiu",
    country: "RO",
    latitude: 45.785833,
    longitude: 24.085556,
    frequencies: ["126.450"],
    region: "Romania",
    volmetName: "Bucharest VOLMET",
    atis: "126.95",
    isActive: true,
  },
  {
    icao: "LSGG",
    iata: "GVA",
    name: "Geneva",
    city: "Geneva",
    country: "CH",
    latitude: 46.238333,
    longitude: 6.109444,
    frequencies: ["126.425"],
    region: "Switzerland",
    volmetName: "Frankfurt VOLMET",
    atis: "124.755",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "LSZH",
    iata: "ZRH",
    name: "Zurich",
    city: "Zurich",
    country: "CH",
    latitude: 47.458056,
    longitude: 8.548056,
    frequencies: ["126.425"],
    region: "Switzerland",
    volmetName: "Frankfurt VOLMET",
    atis: "125.73",
    handlingFrequency: "131.525",
    isActive: true,
  },
  {
    icao: "LTAI",
    iata: "AYT",
    name: "Antalya Intl",
    city: "Antalya Intl",
    country: "TR",
    latitude: 36.900278,
    longitude: 30.792778,
    frequencies: ["126.450"],
    region: "Turkey",
    volmetName: "Istanbul VOLMET",
    atis: "118.27",
    isActive: true,
  },
  {
    icao: "LTAZ",
    iata: "NAV",
    name: "Kapadokya",
    city: "Kapadokya",
    country: "TR",
    latitude: 38.775278,
    longitude: 34.526667,
    frequencies: ["126.450"],
    region: "Turkey",
    volmetName: "Istanbul VOLMET",
    atis: "119.37",
    isActive: true,
  },
  {
    icao: "LTBA",
    iata: "ISL",
    name: "Ataturk Intl",
    city: "Ataturk Intl",
    country: "TR",
    latitude: 40.976111,
    longitude: 28.814167,
    frequencies: ["126.450"],
    region: "Turkey",
    volmetName: "Istanbul VOLMET",
    atis: "128.2",
    isActive: true,
  },
  {
    icao: "LTBJ",
    iata: "ADB",
    name: "Adnan Menderes Intl",
    city: "Adnan Menderes Intl",
    country: "TR",
    latitude: 38.289167,
    longitude: 27.155,
    frequencies: ["126.450"],
    region: "Turkey",
    volmetName: "Istanbul VOLMET",
    atis: "129.2",
    isActive: true,
  },
  {
    icao: "LTBS",
    iata: "DLM",
    name: "Dalaman Intl",
    city: "Dalaman Intl",
    country: "TR",
    latitude: 36.7125,
    longitude: 28.791389,
    frequencies: ["126.450"],
    region: "Turkey",
    volmetName: "Istanbul VOLMET",
    atis: "127.35",
    isActive: true,
  },
  {
    icao: "LTCA",
    iata: "EZS",
    name: "Elazig",
    city: "Elazig",
    country: "TR",
    latitude: 38.597778,
    longitude: 39.281389,
    frequencies: ["126.450"],
    region: "Turkey",
    volmetName: "Istanbul VOLMET",
    atis: "127.95",
    isActive: true,
  },
  {
    icao: "LTCC",
    iata: "DIY",
    name: "Diyarbakir",
    city: "Diyarbakir",
    country: "TR",
    latitude: 37.893611,
    longitude: 40.199861,
    frequencies: ["126.450"],
    region: "Turkey",
    volmetName: "Istanbul VOLMET",
    atis: "118.67",
    isActive: true,
  },
  {
    icao: "LTCG",
    iata: "TZX",
    name: "Trabzon Intl",
    city: "Trabzon Intl",
    country: "TR",
    latitude: 40.995833,
    longitude: 39.785278,
    frequencies: ["126.450"],
    region: "Turkey",
    volmetName: "Istanbul VOLMET",
    atis: "118.62",
    isActive: true,
  },
  {
    icao: "LTDE",
    name: "LTDE",
    city: "LTDE",
    country: "TR",
    frequencies: ["126.450"],
    region: "Turkey",
    volmetName: "Istanbul VOLMET",
    isActive: true,
  },
  {
    icao: "LTFC",
    iata: "ISE",
    name: "Suleyman Demirel",
    city: "Suleyman Demirel",
    country: "TR",
    latitude: 37.855833,
    longitude: 30.366944,
    frequencies: ["126.450"],
    region: "Turkey",
    volmetName: "Istanbul VOLMET",
    atis: "129.02",
    isActive: true,
  },
  {
    icao: "LTFH",
    iata: "SZF",
    name: "Carsamba",
    city: "Carsamba",
    country: "TR",
    latitude: 41.265556,
    longitude: 36.548611,
    frequencies: ["126.450"],
    region: "Turkey",
    volmetName: "Istanbul VOLMET",
    atis: "129.35",
    isActive: true,
  },
  {
    icao: "LTFJ",
    iata: "SAW",
    name: "Sabiha Gokcen Intl",
    city: "Sabiha Gokcen Intl",
    country: "TR",
    latitude: 40.898333,
    longitude: 29.309167,
    frequencies: ["126.450"],
    region: "Turkey",
    volmetName: "Istanbul VOLMET",
    atis: "128.55",
    isActive: true,
  },
  {
    icao: "LUKK",
    iata: "RMO",
    name: "Chisinau Intl",
    city: "Chisinau Intl",
    country: "MD",
    latitude: 46.927778,
    longitude: 28.930833,
    frequencies: ["126.450"],
    region: "Moldova",
    volmetName: "Kiev VOLMET",
    atis: "125.23",
    isActive: true,
  },
  {
    icao: "LWSK",
    iata: "SKP",
    name: "Skopje Intl",
    city: "Skopje Intl",
    country: "MK",
    latitude: 41.961614,
    longitude: 21.621433,
    frequencies: ["126.425"],
    region: "North Macedonia",
    volmetName: "Belgrade VOLMET",
    atis: "130.12",
    isActive: true,
  },
  {
    icao: "LXGB",
    iata: "GIB",
    name: "Gibraltar",
    city: "Gibraltar",
    country: "GI",
    latitude: 36.151169,
    longitude: -5.34975,
    frequencies: ["127.675"],
    region: "Spain",
    volmetName: "Madrid VOLMET",
    isActive: true,
  },
  {
    icao: "LYBE",
    iata: "BEG",
    name: "Nikola Tesla",
    city: "Nikola Tesla",
    country: "RS",
    latitude: 44.819444,
    longitude: 20.306944,
    frequencies: ["126.425"],
    region: "Serbia",
    volmetName: "Belgrade VOLMET",
    atis: "125.02",
    isActive: true,
  },
  {
    icao: "LYPG",
    iata: "TGD",
    name: "Podgorica",
    city: "Podgorica",
    country: "RS",
    latitude: 42.359444,
    longitude: 19.251944,
    frequencies: ["126.425"],
    region: "Montenegro",
    volmetName: "Belgrade VOLMET",
    isActive: true,
  },
  {
    icao: "LZIB",
    iata: "BTS",
    name: "M.r. Stefanik",
    city: "M.r. Stefanik",
    country: "SK",
    latitude: 48.17,
    longitude: 17.212778,
    frequencies: ["126.425"],
    region: "Slovakia",
    volmetName: "Frankfurt VOLMET",
    atis: "128.655",
    isActive: true,
  },
  {
    icao: "OJAI",
    iata: "AMM",
    name: "Queen Alia Intl",
    city: "Queen Alia Intl",
    country: "JO",
    latitude: 31.724128,
    longitude: 35.994622,
    frequencies: ["126.450"],
    region: "Jordan",
    volmetName: "Amman VOLMET",
    atis: "127.6",
    isActive: true,
  },
  {
    icao: "UBBB",
    iata: "GYD",
    name: "Heydar Aliyev Intl",
    city: "Heydar Aliyev Intl",
    country: "AZ",
    latitude: 40.469722,
    longitude: 50.051389,
    frequencies: ["126.450"],
    region: "Azerbaijan",
    volmetName: "Baku VOLMET",
    atis: "126.8",
    isActive: true,
  },
  {
    icao: "UDYZ",
    iata: "EVN",
    name: "Zvartnots",
    city: "Zvartnots",
    country: "AM",
    latitude: 40.147275,
    longitude: 44.395881,
    frequencies: ["126.450"],
    region: "Armenia",
    volmetName: "Yerevan VOLMET",
    atis: "119.5",
    isActive: true,
  },
  {
    icao: "UGTB",
    iata: "TBS",
    name: "Tbilisi",
    city: "Tbilisi",
    country: "GE",
    latitude: 41.669167,
    longitude: 44.954722,
    frequencies: ["126.450"],
    region: "Georgia",
    volmetName: "Tbilisi VOLMET",
    atis: "132.8",
    isActive: true,
  },
  {
    icao: "UKBB",
    iata: "KBP",
    name: "Boryspil Intl",
    city: "Boryspil Intl",
    country: "UA",
    latitude: 50.344722,
    longitude: 30.893333,
    frequencies: ["126.450"],
    region: "Ukraine",
    volmetName: "Kiev VOLMET",
    atis: "125.95",
    isActive: true,
  },
  {
    icao: "UKKK",
    iata: "IEV",
    name: "Zhuliany",
    city: "Zhuliany",
    country: "UA",
    latitude: 50.401944,
    longitude: 30.451944,
    frequencies: ["126.450"],
    region: "Ukraine",
    volmetName: "Kiev VOLMET",
    atis: "126.8",
    isActive: true,
  },
];
