import { Volmet } from "../../volmet/entities/volmet.entity";

export const VOLMET_DATA: Partial<Volmet>[] = [
  // Italy - Major Ryanair bases and destinations
  {
    icao: "LIME",
    iata: "MXP",
    name: "Milan Malpensa Airport",
    city: "Milan",
    country: "IT",
    latitude: 45.6306,
    longitude: 8.72811,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LIPB",
    iata: "BGY",
    name: "Bergamo Orio al Serio Airport",
    city: "Bergamo",
    country: "IT",
    latitude: 45.6745,
    longitude: 9.70417,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LIRF",
    iata: "FCO",
    name: "Rome Fiumicino Airport",
    city: "Rome",
    country: "IT",
    latitude: 41.8003,
    longitude: 12.2389,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LIRA",
    iata: "CIA",
    name: "Rome Ciampino Airport",
    city: "Rome",
    country: "IT",
    latitude: 41.7994,
    longitude: 12.5956,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LICJ",
    iata: "CTA",
    name: "Catania Fontanarossa Airport",
    city: "Catania",
    country: "IT",
    latitude: 37.4668,
    longitude: 15.0664,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LICC",
    iata: "PMO",
    name: "Palermo Airport",
    city: "Palermo",
    country: "IT",
    latitude: 38.182,
    longitude: 13.0991,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LIPZ",
    iata: "VCE",
    name: "Venice Marco Polo Airport",
    city: "Venice",
    country: "IT",
    latitude: 45.5053,
    longitude: 12.3519,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LIRN",
    iata: "NAP",
    name: "Naples Airport",
    city: "Naples",
    country: "IT",
    latitude: 40.886,
    longitude: 14.2908,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LIMJ",
    iata: "GOA",
    name: "Genoa Airport",
    city: "Genoa",
    country: "IT",
    latitude: 44.4134,
    longitude: 8.83722,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LIRS",
    iata: "PSA",
    name: "Pisa Airport",
    city: "Pisa",
    country: "IT",
    latitude: 43.6839,
    longitude: 10.3926,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LIQK",
    iata: "CAG",
    name: "Cagliari Airport",
    city: "Cagliari",
    country: "IT",
    latitude: 39.2515,
    longitude: 9.05443,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LIBR",
    iata: "BRI",
    name: "Bari Airport",
    city: "Bari",
    country: "IT",
    latitude: 41.1384,
    longitude: 16.7607,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LIBP",
    iata: "BDS",
    name: "Brindisi Airport",
    city: "Brindisi",
    country: "IT",
    latitude: 40.6566,
    longitude: 17.9449,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LIRP",
    iata: "PEG",
    name: "Perugia Airport",
    city: "Perugia",
    country: "IT",
    latitude: 43.0402,
    longitude: 12.5088,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LIPR",
    iata: "RMI",
    name: "Rimini Airport",
    city: "Rimini",
    country: "IT",
    latitude: 44.0198,
    longitude: 12.4169,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LIPX",
    iata: "BZO",
    name: "Bolzano Airport",
    city: "Bolzano",
    country: "IT",
    latitude: 46.4619,
    longitude: 11.3298,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LIVT",
    iata: "TRS",
    name: "Trieste Airport",
    city: "Trieste",
    country: "IT",
    latitude: 45.8281,
    longitude: 13.4704,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LIQN",
    iata: "TPS",
    name: "Trapani Airport",
    city: "Trapani",
    country: "IT",
    latitude: 37.9065,
    longitude: 12.4975,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LIAD",
    iata: "AHO",
    name: "Alghero Airport",
    city: "Alghero",
    country: "IT",
    latitude: 40.6323,
    longitude: 8.28563,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  {
    icao: "LIEE",
    iata: "CRV",
    name: "Crotone Airport",
    city: "Crotone",
    country: "IT",
    latitude: 39.0013,
    longitude: 17.0735,
    frequencies: ["127.6"],
    region: "Italy",
    isActive: true,
  },
  // Spain - Major Ryanair bases and destinations
  {
    icao: "LEMD",
    iata: "MAD",
    name: "Madrid Barajas Airport",
    city: "Madrid",
    country: "ES",
    latitude: 40.4983,
    longitude: -3.56764,
    frequencies: ["126.2"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "LEBL",
    iata: "BCN",
    name: "Barcelona El Prat Airport",
    city: "Barcelona",
    country: "ES",
    latitude: 41.2974,
    longitude: 2.08333,
    frequencies: ["126.2"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "LEMG",
    iata: "AGP",
    name: "Malaga Airport",
    city: "Malaga",
    country: "ES",
    latitude: 36.6749,
    longitude: -4.49911,
    frequencies: ["126.2"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "GCLP",
    iata: "LPA",
    name: "Gran Canaria Airport",
    city: "Las Palmas",
    country: "ES",
    latitude: 27.9319,
    longitude: -15.3866,
    frequencies: ["127.6"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "GCFV",
    iata: "FUE",
    name: "Fuerteventura Airport",
    city: "Fuerteventura",
    country: "ES",
    latitude: 28.4527,
    longitude: -13.8638,
    frequencies: ["127.6"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "GCTS",
    iata: "TFS",
    name: "Tenerife South Airport",
    city: "Tenerife",
    country: "ES",
    latitude: 28.0445,
    longitude: -16.5725,
    frequencies: ["127.6"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "GCXO",
    iata: "TFN",
    name: "Tenerife North Airport",
    city: "Tenerife",
    country: "ES",
    latitude: 28.4726,
    longitude: -16.3426,
    frequencies: ["127.6"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "LEAL",
    iata: "ALC",
    name: "Alicante Airport",
    city: "Alicante",
    country: "ES",
    latitude: 38.2822,
    longitude: -0.558167,
    frequencies: ["126.2"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "LEPA",
    iata: "PMI",
    name: "Palma de Mallorca Airport",
    city: "Palma",
    country: "ES",
    latitude: 39.5517,
    longitude: 2.73881,
    frequencies: ["126.2"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "LEIB",
    iata: "IBZ",
    name: "Ibiza Airport",
    city: "Ibiza",
    country: "ES",
    latitude: 38.8729,
    longitude: 1.37332,
    frequencies: ["126.2"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "LESA",
    iata: "SVQ",
    name: "Seville Airport",
    city: "Seville",
    country: "ES",
    latitude: 37.418,
    longitude: -5.8931,
    frequencies: ["126.2"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "LELL",
    iata: "GRO",
    name: "Barcelona Girona Airport",
    city: "Girona",
    country: "ES",
    latitude: 41.9022,
    longitude: 2.75331,
    frequencies: ["126.2"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "LEVT",
    iata: "VLC",
    name: "Valencia Airport",
    city: "Valencia",
    country: "ES",
    latitude: 39.4893,
    longitude: -0.4816,
    frequencies: ["126.2"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "LEZL",
    iata: "ZAZ",
    name: "Zaragoza Airport",
    city: "Zaragoza",
    country: "ES",
    latitude: 41.6644,
    longitude: -1.04236,
    frequencies: ["126.2"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "LERT",
    iata: "SCQ",
    name: "Santiago de Compostela Airport",
    city: "Santiago",
    country: "ES",
    latitude: 42.8958,
    longitude: -8.41536,
    frequencies: ["126.2"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "LECO",
    iata: "BIO",
    name: "Bilbao Airport",
    city: "Bilbao",
    country: "ES",
    latitude: 43.3011,
    longitude: -2.9106,
    frequencies: ["126.2"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "LEJR",
    iata: "RYL",
    name: "Jerez Airport",
    city: "Jerez",
    country: "ES",
    latitude: 36.7553,
    longitude: -6.06047,
    frequencies: ["126.2"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "LPMI",
    iata: "MAH",
    name: "Menorca Airport",
    city: "Menorca",
    country: "ES",
    latitude: 39.8629,
    longitude: 4.21932,
    frequencies: ["126.2"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "GCRR",
    iata: "ACE",
    name: "Lanzarote Airport",
    city: "Lanzarote",
    country: "ES",
    latitude: 28.9454,
    longitude: -13.6053,
    frequencies: ["127.6"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "LEGE",
    iata: "GRX",
    name: "Granada Airport",
    city: "Granada",
    country: "ES",
    latitude: 37.1879,
    longitude: -3.7784,
    frequencies: ["126.2"],
    region: "Spain",
    isActive: true,
  },
  {
    icao: "LEMH",
    iata: "RMU",
    name: "Murcia Airport",
    city: "Murcia",
    country: "ES",
    latitude: 37.7754,
    longitude: -0.94445,
    frequencies: ["126.2"],
    region: "Spain",
    isActive: true,
  },
  // United Kingdom
  {
    icao: "EGSS",
    iata: "STN",
    name: "London Stansted Airport",
    city: "London",
    country: "GB",
    latitude: 51.886,
    longitude: 0.2389,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGLL",
    iata: "LHR",
    name: "London Heathrow Airport",
    city: "London",
    country: "GB",
    latitude: 51.4706,
    longitude: -0.4619,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGKK",
    iata: "LGW",
    name: "London Gatwick Airport",
    city: "London",
    country: "GB",
    latitude: 51.1537,
    longitude: -0.1821,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGCC",
    iata: "MAN",
    name: "Manchester Airport",
    city: "Manchester",
    country: "GB",
    latitude: 53.3537,
    longitude: -2.275,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGJB",
    iata: "GCI",
    name: "Guernsey Airport",
    city: "Guernsey",
    country: "GB",
    latitude: 49.4344,
    longitude: -2.5964,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGJJ",
    iata: "JER",
    name: "Jersey Airport",
    city: "Jersey",
    country: "GB",
    latitude: 49.2077,
    longitude: -2.1954,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGGP",
    iata: "LPL",
    name: "Liverpool John Lennon Airport",
    city: "Liverpool",
    country: "GB",
    latitude: 53.3333,
    longitude: -2.85,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGFF",
    iata: "CWL",
    name: "Cardiff Airport",
    city: "Cardiff",
    country: "GB",
    latitude: 51.3967,
    longitude: -3.3433,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGPD",
    iata: "ABZ",
    name: "Aberdeen Airport",
    city: "Aberdeen",
    country: "GB",
    latitude: 57.2018,
    longitude: -2.1985,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGPH",
    iata: "EDI",
    name: "Edinburgh Airport",
    city: "Edinburgh",
    country: "GB",
    latitude: 55.9508,
    longitude: -3.3615,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGPF",
    iata: "GLA",
    name: "Glasgow Airport",
    city: "Glasgow",
    country: "GB",
    latitude: 55.8642,
    longitude: -4.4331,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGPC",
    iata: "INV",
    name: "Inverness Airport",
    city: "Inverness",
    country: "GB",
    latitude: 57.5434,
    longitude: -4.0476,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGPK",
    iata: "PIK",
    name: "Prestwick Airport",
    city: "Prestwick",
    country: "GB",
    latitude: 55.5066,
    longitude: -4.5867,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGKB",
    iata: "BQH",
    name: "London Biggin Hill Airport",
    city: "London",
    country: "GB",
    latitude: 51.3306,
    longitude: -0.0334,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGBB",
    iata: "BHX",
    name: "Birmingham Airport",
    city: "Birmingham",
    country: "GB",
    latitude: 52.4539,
    longitude: -1.748,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGNX",
    iata: "EMA",
    name: "East Midlands Airport",
    city: "Nottingham",
    country: "GB",
    latitude: 52.831,
    longitude: -1.3285,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGNT",
    iata: "NCL",
    name: "Newcastle Airport",
    city: "Newcastle",
    country: "GB",
    latitude: 55.0375,
    longitude: -1.6917,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGAA",
    iata: "BFS",
    name: "Belfast Aldergrove Airport",
    city: "Belfast",
    country: "GB",
    latitude: 54.6575,
    longitude: -6.2158,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGAC",
    iata: "BHD",
    name: "Belfast City Airport",
    city: "Belfast",
    country: "GB",
    latitude: 54.6184,
    longitude: -5.8722,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  {
    icao: "EGPI",
    iata: "ILY",
    name: "Islay Airport",
    city: "Islay",
    country: "GB",
    latitude: 55.6867,
    longitude: -6.2561,
    frequencies: ["135.37"],
    region: "United Kingdom",
    isActive: true,
  },
  // Ireland
  {
    icao: "EIDW",
    iata: "DUB",
    name: "Dublin Airport",
    city: "Dublin",
    country: "IE",
    latitude: 53.4264,
    longitude: -6.2499,
    frequencies: ["127.6"],
    region: "Ireland",
    isActive: true,
  },
  {
    icao: "EINN",
    iata: "SNN",
    name: "Shannon Airport",
    city: "Shannon",
    country: "IE",
    latitude: 52.7019,
    longitude: -8.9248,
    frequencies: ["127.6"],
    region: "Ireland",
    isActive: true,
  },
  {
    icao: "EICK",
    iata: "ORK",
    name: "Cork Airport",
    city: "Cork",
    country: "IE",
    latitude: 51.8413,
    longitude: -8.4911,
    frequencies: ["127.6"],
    region: "Ireland",
    isActive: true,
  },
  {
    icao: "EIKN",
    iata: "NOC",
    name: "Knock Airport",
    city: "Knock",
    country: "IE",
    latitude: 53.9105,
    longitude: -8.8172,
    frequencies: ["127.6"],
    region: "Ireland",
    isActive: true,
  },
  {
    icao: "EIME",
    iata: "GWY",
    name: "Galway Airport",
    city: "Galway",
    country: "IE",
    latitude: 53.3019,
    longitude: -9.0634,
    frequencies: ["127.6"],
    region: "Ireland",
    isActive: true,
  },
  {
    icao: "EICA",
    iata: "CFN",
    name: "Donegal Airport",
    city: "Donegal",
    country: "IE",
    latitude: 55.0459,
    longitude: -8.3426,
    frequencies: ["127.6"],
    region: "Ireland",
    isActive: true,
  },
  {
    icao: "EIKY",
    iata: "KIR",
    name: "Kerry Airport",
    city: "Kerry",
    country: "IE",
    latitude: 52.1811,
    longitude: -9.5258,
    frequencies: ["127.6"],
    region: "Ireland",
    isActive: true,
  },
  // Portugal
  {
    icao: "LPPT",
    iata: "LIS",
    name: "Lisbon Humberto Delgado Airport",
    city: "Lisbon",
    country: "PT",
    latitude: 38.7756,
    longitude: -9.1354,
    frequencies: ["127.6"],
    region: "Portugal",
    isActive: true,
  },
  {
    icao: "LPPR",
    iata: "OPO",
    name: "Porto Airport",
    city: "Porto",
    country: "PT",
    latitude: 41.2481,
    longitude: -8.6814,
    frequencies: ["127.6"],
    region: "Portugal",
    isActive: true,
  },
  {
    icao: "LPFR",
    iata: "FAO",
    name: "Faro Airport",
    city: "Faro",
    country: "PT",
    latitude: 37.0144,
    longitude: -7.9659,
    frequencies: ["127.6"],
    region: "Portugal",
    isActive: true,
  },
  {
    icao: "LPPA",
    iata: "PDL",
    name: "Ponta Delgada Airport",
    city: "Ponta Delgada",
    country: "PT",
    latitude: 37.7412,
    longitude: -25.6976,
    frequencies: ["127.6"],
    region: "Portugal",
    isActive: true,
  },
  {
    icao: "LPAZ",
    iata: "TER",
    name: "Terceira Airport",
    city: "Terceira",
    country: "PT",
    latitude: 38.7289,
    longitude: -27.2354,
    frequencies: ["127.6"],
    region: "Portugal",
    isActive: true,
  },
  {
    icao: "LPMA",
    iata: "FNC",
    name: "Funchal Madeira Airport",
    city: "Funchal",
    country: "PT",
    latitude: 32.6979,
    longitude: -16.7745,
    frequencies: ["127.6"],
    region: "Portugal",
    isActive: true,
  },
  {
    icao: "LPPS",
    iata: "PXO",
    name: "Porto Santo Airport",
    city: "Porto Santo",
    country: "PT",
    latitude: 33.0731,
    longitude: -16.3495,
    frequencies: ["127.6"],
    region: "Portugal",
    isActive: true,
  },
  // France
  {
    icao: "LFPG",
    iata: "CDG",
    name: "Paris Charles de Gaulle Airport",
    city: "Paris",
    country: "FR",
    latitude: 49.0097,
    longitude: 2.5479,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  {
    icao: "LFPO",
    iata: "ORY",
    name: "Paris Orly Airport",
    city: "Paris",
    country: "FR",
    latitude: 48.7262,
    longitude: 2.3652,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  {
    icao: "LFBO",
    iata: "TLS",
    name: "Toulouse Blagnac Airport",
    city: "Toulouse",
    country: "FR",
    latitude: 43.635,
    longitude: 1.3678,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  {
    icao: "LFMN",
    iata: "NCE",
    name: "Nice Cote d'Azur Airport",
    city: "Nice",
    country: "FR",
    latitude: 43.6584,
    longitude: 7.2159,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  {
    icao: "LFML",
    iata: "MRS",
    name: "Marseille Provence Airport",
    city: "Marseille",
    country: "FR",
    latitude: 43.4393,
    longitude: 5.2214,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  {
    icao: "LFBH",
    iata: "BIQ",
    name: "Biarritz Airport",
    city: "Biarritz",
    country: "FR",
    latitude: 43.4723,
    longitude: -1.5527,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  {
    icao: "LFBD",
    iata: "BOD",
    name: "Bordeaux Merignac Airport",
    city: "Bordeaux",
    country: "FR",
    latitude: 44.8283,
    longitude: -0.7156,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  {
    icao: "LFLL",
    iata: "LYS",
    name: "Lyon Saint Exupery Airport",
    city: "Lyon",
    country: "FR",
    latitude: 45.7256,
    longitude: 5.0811,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  {
    icao: "LFBN",
    iata: "NTE",
    name: "Nantes Atlantique Airport",
    city: "Nantes",
    country: "FR",
    latitude: 47.1532,
    longitude: -1.6107,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  {
    icao: "LFST",
    iata: "SXB",
    name: "Strasbourg Airport",
    city: "Strasbourg",
    country: "FR",
    latitude: 48.5498,
    longitude: 7.6435,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  {
    icao: "LFMT",
    iata: "MPL",
    name: "Montpellier Airport",
    city: "Montpellier",
    country: "FR",
    latitude: 43.5779,
    longitude: 3.9631,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  {
    icao: "LFBT",
    iata: "LDE",
    name: "Tarbes Airport",
    city: "Tarbes",
    country: "FR",
    latitude: 43.3556,
    longitude: 0.0014,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  {
    icao: "LFRN",
    iata: "RNS",
    name: "Rennes Airport",
    city: "Rennes",
    country: "FR",
    latitude: 48.0695,
    longitude: -1.7244,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  {
    icao: "LFRO",
    iata: "DNR",
    name: "Dinard Airport",
    city: "Dinard",
    country: "FR",
    latitude: 48.8525,
    longitude: -2.0746,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  {
    icao: "LFKJ",
    iata: "AJA",
    name: "Ajaccio Airport",
    city: "Ajaccio",
    country: "FR",
    latitude: 41.9258,
    longitude: 8.7934,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  {
    icao: "LFMF",
    iata: "FSC",
    name: "Figari Airport",
    city: "Figari",
    country: "FR",
    latitude: 41.6245,
    longitude: 9.0896,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  {
    icao: "LFKB",
    iata: "BIA",
    name: "Bastia Airport",
    city: "Bastia",
    country: "FR",
    latitude: 42.5508,
    longitude: 9.4855,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  {
    icao: "LFKC",
    iata: "CLY",
    name: "Calvi Airport",
    city: "Calvi",
    country: "FR",
    latitude: 42.5287,
    longitude: 8.7946,
    frequencies: ["126.0"],
    region: "France",
    isActive: true,
  },
  // Germany
  {
    icao: "EDDF",
    iata: "FRA",
    name: "Frankfurt Airport",
    city: "Frankfurt",
    country: "DE",
    latitude: 50.0379,
    longitude: 8.5622,
    frequencies: ["127.6"],
    region: "Germany",
    isActive: true,
  },
  {
    icao: "EDDB",
    iata: "BER",
    name: "Berlin Brandenburg Airport",
    city: "Berlin",
    country: "DE",
    latitude: 52.3667,
    longitude: 13.5033,
    frequencies: ["126.35"],
    region: "Germany",
    isActive: true,
  },
  {
    icao: "EDDM",
    iata: "MUC",
    name: "Munich Airport",
    city: "Munich",
    country: "DE",
    latitude: 48.3537,
    longitude: 11.775,
    frequencies: ["127.6"],
    region: "Germany",
    isActive: true,
  },
  {
    icao: "EDDL",
    iata: "DUS",
    name: "Dusseldorf Airport",
    city: "Dusseldorf",
    country: "DE",
    latitude: 51.2895,
    longitude: 6.7668,
    frequencies: ["127.6"],
    region: "Germany",
    isActive: true,
  },
  {
    icao: "EDDH",
    iata: "HAM",
    name: "Hamburg Airport",
    city: "Hamburg",
    country: "DE",
    latitude: 53.6304,
    longitude: 10.0065,
    frequencies: ["127.6"],
    region: "Germany",
    isActive: true,
  },
  {
    icao: "EDDK",
    iata: "CGN",
    name: "Cologne Bonn Airport",
    city: "Cologne",
    country: "DE",
    latitude: 50.8659,
    longitude: 7.1427,
    frequencies: ["127.6"],
    region: "Germany",
    isActive: true,
  },
  {
    icao: "EDDW",
    iata: "BRE",
    name: "Bremen Airport",
    city: "Bremen",
    country: "DE",
    latitude: 53.0475,
    longitude: 8.7867,
    frequencies: ["127.6"],
    region: "Germany",
    isActive: true,
  },
  {
    icao: "EDDV",
    iata: "HAJ",
    name: "Hannover Airport",
    city: "Hannover",
    country: "DE",
    latitude: 52.4611,
    longitude: 9.685,
    frequencies: ["127.6"],
    region: "Germany",
    isActive: true,
  },
  {
    icao: "EDDE",
    iata: "LEJ",
    name: "Leipzig Halle Airport",
    city: "Leipzig",
    country: "DE",
    latitude: 51.4324,
    longitude: 12.2416,
    frequencies: ["127.6"],
    region: "Germany",
    isActive: true,
  },
  {
    icao: "EDDS",
    iata: "STR",
    name: "Stuttgart Airport",
    city: "Stuttgart",
    country: "DE",
    latitude: 48.6899,
    longitude: 9.222,
    frequencies: ["127.6"],
    region: "Germany",
    isActive: true,
  },
  {
    icao: "EDDN",
    iata: "NUE",
    name: "Nuremberg Airport",
    city: "Nuremberg",
    country: "DE",
    latitude: 49.4987,
    longitude: 11.0669,
    frequencies: ["127.6"],
    region: "Germany",
    isActive: true,
  },
  {
    icao: "EDDC",
    iata: "DRS",
    name: "Dresden Airport",
    city: "Dresden",
    country: "DE",
    latitude: 51.1348,
    longitude: 13.7681,
    frequencies: ["127.6"],
    region: "Germany",
    isActive: true,
  },
  {
    icao: "EDHI",
    iata: "XHW",
    name: "Hamburg Finkenwerder Airport",
    city: "Hamburg",
    country: "DE",
    latitude: 53.5414,
    longitude: 9.9647,
    frequencies: ["127.6"],
    region: "Germany",
    isActive: true,
  },
  // Netherlands
  {
    icao: "EHAM",
    iata: "AMS",
    name: "Amsterdam Schiphol Airport",
    city: "Amsterdam",
    country: "NL",
    latitude: 52.3105,
    longitude: 4.7683,
    frequencies: ["119.75"],
    region: "Netherlands",
    isActive: true,
  },
  {
    icao: "EHRD",
    iata: "RTM",
    name: "Rotterdam The Hague Airport",
    city: "Rotterdam",
    country: "NL",
    latitude: 51.9569,
    longitude: 4.4372,
    frequencies: ["119.75"],
    region: "Netherlands",
    isActive: true,
  },
  {
    icao: "EHBK",
    iata: "MST",
    name: "Maastricht Aachen Airport",
    city: "Maastricht",
    country: "NL",
    latitude: 50.9152,
    longitude: 5.7766,
    frequencies: ["119.75"],
    region: "Netherlands",
    isActive: true,
  },
  {
    icao: "EHLE",
    iata: "LEY",
    name: "Lelystad Airport",
    city: "Lelystad",
    country: "NL",
    latitude: 52.4587,
    longitude: 5.5302,
    frequencies: ["119.75"],
    region: "Netherlands",
    isActive: true,
  },
  {
    icao: "EHEH",
    iata: "EIN",
    name: "Eindhoven Airport",
    city: "Eindhoven",
    country: "NL",
    latitude: 51.4501,
    longitude: 5.3743,
    frequencies: ["119.75"],
    region: "Netherlands",
    isActive: true,
  },
  // Belgium
  {
    icao: "EBBR",
    iata: "BRU",
    name: "Brussels Airport",
    city: "Brussels",
    country: "BE",
    latitude: 50.9014,
    longitude: 4.4844,
    frequencies: ["127.6"],
    region: "Belgium",
    isActive: true,
  },
  {
    icao: "EBCI",
    iata: "CRL",
    name: "Brussels South Charleroi Airport",
    city: "Charleroi",
    country: "BE",
    latitude: 50.4592,
    longitude: 4.4538,
    frequencies: ["127.6"],
    region: "Belgium",
    isActive: true,
  },
  {
    icao: "EBLT",
    iata: "LGG",
    name: "Liege Airport",
    city: "Liege",
    country: "BE",
    latitude: 50.6374,
    longitude: 5.4432,
    frequencies: ["127.6"],
    region: "Belgium",
    isActive: true,
  },
  {
    icao: "EBOS",
    iata: "OST",
    name: "Ostend Bruges Airport",
    city: "Ostend",
    country: "BE",
    latitude: 51.1994,
    longitude: 2.8638,
    frequencies: ["127.6"],
    region: "Belgium",
    isActive: true,
  },
  {
    icao: "EBMB",
    iata: "ANR",
    name: "Antwerp International Airport",
    city: "Antwerp",
    country: "BE",
    latitude: 51.1894,
    longitude: 4.4602,
    frequencies: ["127.6"],
    region: "Belgium",
    isActive: true,
  },
  // Poland
  {
    icao: "EPWA",
    iata: "WAW",
    name: "Warsaw Chopin Airport",
    city: "Warsaw",
    country: "PL",
    latitude: 52.1657,
    longitude: 20.9671,
    frequencies: ["127.6"],
    region: "Poland",
    isActive: true,
  },
  {
    icao: "EPKK",
    iata: "KRK",
    name: "Krakow Airport",
    city: "Krakow",
    country: "PL",
    latitude: 50.0777,
    longitude: 19.7848,
    frequencies: ["127.6"],
    region: "Poland",
    isActive: true,
  },
  {
    icao: "EPGD",
    iata: "GDN",
    name: "Gdansk Lech Walesa Airport",
    city: "Gdansk",
    country: "PL",
    latitude: 54.3776,
    longitude: 18.4662,
    frequencies: ["127.6"],
    region: "Poland",
    isActive: true,
  },
  {
    icao: "EPWR",
    iata: "WRO",
    name: "Wroclaw Airport",
    city: "Wroclaw",
    country: "PL",
    latitude: 51.1027,
    longitude: 16.8858,
    frequencies: ["127.6"],
    region: "Poland",
    isActive: true,
  },
  {
    icao: "EPPO",
    iata: "POZ",
    name: "Poznan Airport",
    city: "Poznan",
    country: "PL",
    latitude: 52.421,
    longitude: 16.8263,
    frequencies: ["127.6"],
    region: "Poland",
    isActive: true,
  },
  {
    icao: "EPKT",
    iata: "KTW",
    name: "Katowice Airport",
    city: "Katowice",
    country: "PL",
    latitude: 50.4743,
    longitude: 19.08,
    frequencies: ["127.6"],
    region: "Poland",
    isActive: true,
  },
  {
    icao: "EPLU",
    iata: "LUZ",
    name: "Lublin Airport",
    city: "Lublin",
    country: "PL",
    latitude: 51.2351,
    longitude: 22.6985,
    frequencies: ["127.6"],
    region: "Poland",
    isActive: true,
  },
  {
    icao: "EPRZ",
    iata: "RZE",
    name: "Rzeszow Airport",
    city: "Rzeszow",
    country: "PL",
    latitude: 50.1094,
    longitude: 22.0547,
    frequencies: ["127.6"],
    region: "Poland",
    isActive: true,
  },
  {
    icao: "EPSY",
    iata: "SZZ",
    name: "Szczecin Airport",
    city: "Szczecin",
    country: "PL",
    latitude: 53.5835,
    longitude: 14.1775,
    frequencies: ["127.6"],
    region: "Poland",
    isActive: true,
  },
  {
    icao: "EPSC",
    iata: "WMI",
    name: "Modlin Airport",
    city: "Warsaw",
    country: "PL",
    latitude: 52.449,
    longitude: 20.6702,
    frequencies: ["127.6"],
    region: "Poland",
    isActive: true,
  },
  // Greece
  {
    icao: "LGAV",
    iata: "ATH",
    name: "Athens International Airport",
    city: "Athens",
    country: "GR",
    latitude: 37.9364,
    longitude: 23.9445,
    frequencies: ["127.6"],
    region: "Greece",
    isActive: true,
  },
  {
    icao: "LGTS",
    iata: "SKG",
    name: "Thessaloniki Airport",
    city: "Thessaloniki",
    country: "GR",
    latitude: 40.5197,
    longitude: 22.9709,
    frequencies: ["127.6"],
    region: "Greece",
    isActive: true,
  },
  {
    icao: "LGKR",
    iata: "CFU",
    name: "Corfu Airport",
    city: "Corfu",
    country: "GR",
    latitude: 39.6019,
    longitude: 19.9117,
    frequencies: ["127.6"],
    region: "Greece",
    isActive: true,
  },
  {
    icao: "LGIR",
    iata: "HER",
    name: "Heraklion Airport",
    city: "Heraklion",
    country: "GR",
    latitude: 35.3397,
    longitude: 25.1803,
    frequencies: ["127.6"],
    region: "Greece",
    isActive: true,
  },
  {
    icao: "LGSM",
    iata: "SMI",
    name: "Samos Airport",
    city: "Samos",
    country: "GR",
    latitude: 37.6939,
    longitude: 26.9128,
    frequencies: ["127.6"],
    region: "Greece",
    isActive: true,
  },
  {
    icao: "LGKP",
    iata: "EFL",
    name: "Kephalonia Airport",
    city: "Kephalonia",
    country: "GR",
    latitude: 38.1189,
    longitude: 20.5054,
    frequencies: ["127.6"],
    region: "Greece",
    isActive: true,
  },
  {
    icao: "LGMK",
    iata: "JMK",
    name: "Mykonos Airport",
    city: "Mykonos",
    country: "GR",
    latitude: 37.4351,
    longitude: 25.3481,
    frequencies: ["127.6"],
    region: "Greece",
    isActive: true,
  },
  {
    icao: "LGSA",
    iata: "JTR",
    name: "Santorini Airport",
    city: "Santorini",
    country: "GR",
    latitude: 36.3992,
    longitude: 25.4793,
    frequencies: ["127.6"],
    region: "Greece",
    isActive: true,
  },
  {
    icao: "LGKL",
    iata: "KGS",
    name: "Kos Airport",
    city: "Kos",
    country: "GR",
    latitude: 36.7933,
    longitude: 26.9407,
    frequencies: ["127.6"],
    region: "Greece",
    isActive: true,
  },
  {
    icao: "LGRJ",
    iata: "RHO",
    name: "Rhodes Airport",
    city: "Rhodes",
    country: "GR",
    latitude: 36.4054,
    longitude: 28.0862,
    frequencies: ["127.6"],
    region: "Greece",
    isActive: true,
  },
  {
    icao: "LGZA",
    iata: "ZTH",
    name: "Zakynthos Airport",
    city: "Zakynthos",
    country: "GR",
    latitude: 37.7508,
    longitude: 20.8874,
    frequencies: ["127.6"],
    region: "Greece",
    isActive: true,
  },
  {
    icao: "LGRP",
    iata: "RHO",
    name: "Rhodes Parthenisi Airport",
    city: "Rhodes",
    country: "GR",
    latitude: 36.4054,
    longitude: 28.0862,
    frequencies: ["127.6"],
    region: "Greece",
    isActive: true,
  },
  {
    icao: "LGLM",
    iata: "LXS",
    name: "Lemnos Airport",
    city: "Lemnos",
    country: "GR",
    latitude: 39.9389,
    longitude: 25.2348,
    frequencies: ["127.6"],
    region: "Greece",
    isActive: true,
  },
  {
    icao: "LGKV",
    iata: "KVA",
    name: "Kavala Airport",
    city: "Kavala",
    country: "GR",
    latitude: 40.9122,
    longitude: 24.0507,
    frequencies: ["127.6"],
    region: "Greece",
    isActive: true,
  },
  {
    icao: "LGBA",
    iata: "ATH",
    name: "Athens Hellinikon Airport",
    city: "Athens",
    country: "GR",
    latitude: 37.8947,
    longitude: 23.7331,
    frequencies: ["127.6"],
    region: "Greece",
    isActive: true,
  },
  // Malta
  {
    icao: "LMML",
    iata: "MLA",
    name: "Malta International Airport",
    city: "Malta",
    country: "MT",
    latitude: 35.8575,
    longitude: 14.4775,
    frequencies: ["127.6"],
    region: "Malta",
    isActive: true,
  },
  // Croatia
  {
    icao: "LDZA",
    iata: "ZAG",
    name: "Zagreb Airport",
    city: "Zagreb",
    country: "HR",
    latitude: 45.7429,
    longitude: 16.0688,
    frequencies: ["127.6"],
    region: "Croatia",
    isActive: true,
  },
  {
    icao: "LDDU",
    iata: "DBV",
    name: "Dubrovnik Airport",
    city: "Dubrovnik",
    country: "HR",
    latitude: 42.5614,
    longitude: 18.2682,
    frequencies: ["127.6"],
    region: "Croatia",
    isActive: true,
  },
  {
    icao: "LDSP",
    iata: "SPU",
    name: "Split Airport",
    city: "Split",
    country: "HR",
    latitude: 43.5389,
    longitude: 16.298,
    frequencies: ["127.6"],
    region: "Croatia",
    isActive: true,
  },
  {
    icao: "LDZL",
    iata: "ZAD",
    name: "Zadar Airport",
    city: "Zadar",
    country: "HR",
    latitude: 44.0909,
    longitude: 15.3477,
    frequencies: ["127.6"],
    region: "Croatia",
    isActive: true,
  },
  {
    icao: "LDPL",
    iata: "PUY",
    name: "Pula Airport",
    city: "Pula",
    country: "HR",
    latitude: 44.8903,
    longitude: 13.9281,
    frequencies: ["127.6"],
    region: "Croatia",
    isActive: true,
  },
  {
    icao: "LDSB",
    iata: "BWK",
    name: "Brac Airport",
    city: "Brac",
    country: "HR",
    latitude: 43.3415,
    longitude: 16.6946,
    frequencies: ["127.6"],
    region: "Croatia",
    isActive: true,
  },
  {
    icao: "LDOR",
    iata: "OSI",
    name: "Osijek Airport",
    city: "Osijek",
    country: "HR",
    latitude: 45.4428,
    longitude: 18.8018,
    frequencies: ["127.6"],
    region: "Croatia",
    isActive: true,
  },
  {
    icao: "LDRI",
    iata: "RJK",
    name: "Rijeka Airport",
    city: "Rijeka",
    country: "HR",
    latitude: 45.2192,
    longitude: 14.5699,
    frequencies: ["127.6"],
    region: "Croatia",
    isActive: true,
  },
  // Morocco
  {
    icao: "GMMX",
    iata: "RAK",
    name: "Marrakech Menara Airport",
    city: "Marrakech",
    country: "MA",
    latitude: 31.6069,
    longitude: -8.0363,
    frequencies: ["127.6"],
    region: "Morocco",
    isActive: true,
  },
  {
    icao: "GMAD",
    iata: "AGA",
    name: "Agadir Al Massira Airport",
    city: "Agadir",
    country: "MA",
    latitude: 30.325,
    longitude: -9.4136,
    frequencies: ["127.6"],
    region: "Morocco",
    isActive: true,
  },
  {
    icao: "GMFF",
    iata: "FEZ",
    name: "Fes Saiss Airport",
    city: "Fes",
    country: "MA",
    latitude: 33.9342,
    longitude: -5.0074,
    frequencies: ["127.6"],
    region: "Morocco",
    isActive: true,
  },
  {
    icao: "GMTT",
    iata: "TNG",
    name: "Tangier Ibn Battouta Airport",
    city: "Tangier",
    country: "MA",
    latitude: 35.7269,
    longitude: -5.9169,
    frequencies: ["127.6"],
    region: "Morocco",
    isActive: true,
  },
  {
    icao: "GMMN",
    iata: "CMN",
    name: "Casablanca Mohammed V Airport",
    city: "Casablanca",
    country: "MA",
    latitude: 33.3675,
    longitude: -7.59,
    frequencies: ["127.6"],
    region: "Morocco",
    isActive: true,
  },
  {
    icao: "GMMA",
    iata: "AHU",
    name: "Al Hoceima Airport",
    city: "Al Hoceima",
    country: "MA",
    latitude: 35.1765,
    longitude: -3.8397,
    frequencies: ["127.6"],
    region: "Morocco",
    isActive: true,
  },
  {
    icao: "GMMZ",
    iata: "BBZ",
    name: "Beni Mellal Airport",
    city: "Beni Mellal",
    country: "MA",
    latitude: 32.4241,
    longitude: -6.3644,
    frequencies: ["127.6"],
    region: "Morocco",
    isActive: true,
  },
  {
    icao: "GMTA",
    iata: "TTU",
    name: "Tetouan Airport",
    city: "Tetouan",
    country: "MA",
    latitude: 35.5879,
    longitude: -5.3332,
    frequencies: ["127.6"],
    region: "Morocco",
    isActive: true,
  },
  {
    icao: "GMMI",
    iata: "NDR",
    name: "Nador Airport",
    city: "Nador",
    country: "MA",
    latitude: 34.9958,
    longitude: -3.0234,
    frequencies: ["127.6"],
    region: "Morocco",
    isActive: true,
  },
  {
    icao: "GMFK",
    iata: "EMW",
    name: "El Jadida Airport",
    city: "El Jadida",
    country: "MA",
    latitude: 33.2316,
    longitude: -8.4256,
    frequencies: ["127.6"],
    region: "Morocco",
    isActive: true,
  },
  // Bulgaria
  {
    icao: "LBSF",
    iata: "SOF",
    name: "Sofia Airport",
    city: "Sofia",
    country: "BG",
    latitude: 42.6952,
    longitude: 23.4062,
    frequencies: ["127.6"],
    region: "Bulgaria",
    isActive: true,
  },
  {
    icao: "LBWN",
    iata: "VAR",
    name: "Varna Airport",
    city: "Varna",
    country: "BG",
    latitude: 43.2326,
    longitude: 27.8251,
    frequencies: ["127.6"],
    region: "Bulgaria",
    isActive: true,
  },
  {
    icao: "LBBD",
    iata: "BOJ",
    name: "Bourgas Airport",
    city: "Bourgas",
    country: "BG",
    latitude: 42.5698,
    longitude: 27.4973,
    frequencies: ["127.6"],
    region: "Bulgaria",
    isActive: true,
  },
  {
    icao: "LBPD",
    iata: "PDV",
    name: "Plovdiv Airport",
    city: "Plovdiv",
    country: "BG",
    latitude: 42.0672,
    longitude: 24.8555,
    frequencies: ["127.6"],
    region: "Bulgaria",
    isActive: true,
  },
  // Romania
  {
    icao: "LROP",
    iata: "OTP",
    name: "Bucharest Henri Coanda Airport",
    city: "Bucharest",
    country: "RO",
    latitude: 44.5711,
    longitude: 26.085,
    frequencies: ["127.6"],
    region: "Romania",
    isActive: true,
  },
  {
    icao: "LRCL",
    iata: "CLJ",
    name: "Cluj Napoca Airport",
    city: "Cluj Napoca",
    country: "RO",
    latitude: 46.7852,
    longitude: 23.6862,
    frequencies: ["127.6"],
    region: "Romania",
    isActive: true,
  },
  {
    icao: "LRTC",
    iata: "TSR",
    name: "Timisoara Traian Vuia Airport",
    city: "Timisoara",
    country: "RO",
    latitude: 45.8075,
    longitude: 21.266,
    frequencies: ["127.6"],
    region: "Romania",
    isActive: true,
  },
  // Hungary
  {
    icao: "LHBP",
    iata: "BUD",
    name: "Budapest Ferenc Liszt Airport",
    city: "Budapest",
    country: "HU",
    latitude: 47.4298,
    longitude: 19.2611,
    frequencies: ["127.6"],
    region: "Hungary",
    isActive: true,
  },
  // Czech Republic
  {
    icao: "LKPR",
    iata: "PRG",
    name: "Prague Vaclav Havel Airport",
    city: "Prague",
    country: "CZ",
    latitude: 50.1008,
    longitude: 14.2632,
    frequencies: ["127.6"],
    region: "Czech Republic",
    isActive: true,
  },
  // Austria
  {
    icao: "LOWW",
    iata: "VIE",
    name: "Vienna International Airport",
    city: "Vienna",
    country: "AT",
    latitude: 48.1103,
    longitude: 16.5697,
    frequencies: ["127.6"],
    region: "Austria",
    isActive: true,
  },
  // Switzerland
  {
    icao: "LSZH",
    iata: "ZRH",
    name: "Zurich Airport",
    city: "Zurich",
    country: "CH",
    latitude: 47.4582,
    longitude: 8.5555,
    frequencies: ["127.6"],
    region: "Switzerland",
    isActive: true,
  },
  {
    icao: "LSGG",
    iata: "GVA",
    name: "Geneva Airport",
    city: "Geneva",
    country: "CH",
    latitude: 46.238,
    longitude: 6.1089,
    frequencies: ["127.6"],
    region: "Switzerland",
    isActive: true,
  },
  {
    icao: "LSZB",
    iata: "BRN",
    name: "Bern Airport",
    city: "Bern",
    country: "CH",
    latitude: 46.9124,
    longitude: 7.4966,
    frequencies: ["127.6"],
    region: "Switzerland",
    isActive: true,
  },
  {
    icao: "LSZS",
    iata: "ACH",
    name: "St. Gallen Airport",
    city: "St. Gallen",
    country: "CH",
    latitude: 47.4896,
    longitude: 9.5586,
    frequencies: ["127.6"],
    region: "Switzerland",
    isActive: true,
  },
  // Denmark
  {
    icao: "EKCH",
    iata: "CPH",
    name: "Copenhagen Airport",
    city: "Copenhagen",
    country: "DK",
    latitude: 55.618,
    longitude: 12.6508,
    frequencies: ["127.6"],
    region: "Denmark",
    isActive: true,
  },
  {
    icao: "EKKA",
    iata: "AAR",
    name: "Aarhus Airport",
    city: "Aarhus",
    country: "DK",
    latitude: 56.2993,
    longitude: 10.219,
    frequencies: ["127.6"],
    region: "Denmark",
    isActive: true,
  },
  {
    icao: "EKBI",
    iata: "BLL",
    name: "Billund Airport",
    city: "Billund",
    country: "DK",
    latitude: 55.7403,
    longitude: 9.1518,
    frequencies: ["127.6"],
    region: "Denmark",
    isActive: true,
  },
  // Sweden
  {
    icao: "ESSA",
    iata: "ARN",
    name: "Stockholm Arlanda Airport",
    city: "Stockholm",
    country: "SE",
    latitude: 59.6519,
    longitude: 17.9186,
    frequencies: ["127.6"],
    region: "Sweden",
    isActive: true,
  },
  {
    icao: "ESMS",
    iata: "MMX",
    name: "Malmo Airport",
    city: "Malmo",
    country: "SE",
    latitude: 55.5363,
    longitude: 13.3762,
    frequencies: ["127.6"],
    region: "Sweden",
    isActive: true,
  },
  {
    icao: "ESGG",
    iata: "GOT",
    name: "Gothenburg Landvetter Airport",
    city: "Gothenburg",
    country: "SE",
    latitude: 57.6628,
    longitude: 12.2798,
    frequencies: ["127.6"],
    region: "Sweden",
    isActive: true,
  },
  // Norway
  {
    icao: "ENGM",
    iata: "OSL",
    name: "Oslo Gardermoen Airport",
    city: "Oslo",
    country: "NO",
    latitude: 60.1976,
    longitude: 11.1004,
    frequencies: ["127.6"],
    region: "Norway",
    isActive: true,
  },
  {
    icao: "ENBR",
    iata: "BGO",
    name: "Bergen Airport",
    city: "Bergen",
    country: "NO",
    latitude: 60.2934,
    longitude: 5.2181,
    frequencies: ["127.6"],
    region: "Norway",
    isActive: true,
  },
  {
    icao: "ENZV",
    iata: "SVG",
    name: "Stavanger Airport",
    city: "Stavanger",
    country: "NO",
    latitude: 58.8767,
    longitude: 5.6378,
    frequencies: ["127.6"],
    region: "Norway",
    isActive: true,
  },
  {
    icao: "ENTC",
    iata: "TRD",
    name: "Trondheim Airport",
    city: "Trondheim",
    country: "NO",
    latitude: 63.4578,
    longitude: 10.924,
    frequencies: ["127.6"],
    region: "Norway",
    isActive: true,
  },
  // Finland
  {
    icao: "EFHK",
    iata: "HEL",
    name: "Helsinki Vantaa Airport",
    city: "Helsinki",
    country: "FI",
    latitude: 60.3172,
    longitude: 24.9633,
    frequencies: ["127.6"],
    region: "Finland",
    isActive: true,
  },
  {
    icao: "EFTU",
    iata: "TKU",
    name: "Turku Airport",
    city: "Turku",
    country: "FI",
    latitude: 60.5141,
    longitude: 22.2628,
    frequencies: ["127.6"],
    region: "Finland",
    isActive: true,
  },
  {
    icao: "EFTP",
    iata: "TMP",
    name: "Tampere Pirkkala Airport",
    city: "Tampere",
    country: "FI",
    latitude: 61.4142,
    longitude: 23.6044,
    frequencies: ["127.6"],
    region: "Finland",
    isActive: true,
  },
  // Iceland
  {
    icao: "BIKF",
    iata: "KEF",
    name: "Reykjavik Keflavik Airport",
    city: "Reykjavik",
    country: "IS",
    latitude: 63.985,
    longitude: -22.6056,
    frequencies: ["127.6"],
    region: "Iceland",
    isActive: true,
  },
  {
    icao: "BIRK",
    iata: "RKV",
    name: "Reykjavik Airport",
    city: "Reykjavik",
    country: "IS",
    latitude: 64.13,
    longitude: -21.9406,
    frequencies: ["127.6"],
    region: "Iceland",
    isActive: true,
  },
  // Latvia
  {
    icao: "EVRA",
    iata: "RIX",
    name: "Riga International Airport",
    city: "Riga",
    country: "LV",
    latitude: 56.9226,
    longitude: 23.9711,
    frequencies: ["127.6"],
    region: "Latvia",
    isActive: true,
  },
  // Estonia
  {
    icao: "EETN",
    iata: "TLL",
    name: "Tallinn Airport",
    city: "Tallinn",
    country: "EE",
    latitude: 59.4133,
    longitude: 24.504,
    frequencies: ["127.6"],
    region: "Estonia",
    isActive: true,
  },
  // Lithuania
  {
    icao: "EYVI",
    iata: "VNO",
    name: "Vilnius Airport",
    city: "Vilnius",
    country: "LT",
    latitude: 54.6342,
    longitude: 25.2848,
    frequencies: ["127.6"],
    region: "Lithuania",
    isActive: true,
  },
  {
    icao: "EYKA",
    iata: "KUN",
    name: "Kaunas Airport",
    city: "Kaunas",
    country: "LT",
    latitude: 54.9639,
    longitude: 24.0837,
    frequencies: ["127.6"],
    region: "Lithuania",
    isActive: true,
  },
  {
    icao: "EYPA",
    iata: "PLQ",
    name: "Palanga Airport",
    city: "Palanga",
    country: "LT",
    latitude: 55.975,
    longitude: 21.3117,
    frequencies: ["127.6"],
    region: "Lithuania",
    isActive: true,
  },
  // Bosnia and Herzegovina
  {
    icao: "LQSA",
    iata: "SJJ",
    name: "Sarajevo Airport",
    city: "Sarajevo",
    country: "BA",
    latitude: 43.8263,
    longitude: 18.3315,
    frequencies: ["127.6"],
    region: "Bosnia",
    isActive: true,
  },
  {
    icao: "LQMO",
    iata: "OMO",
    name: "Mostar Airport",
    city: "Mostar",
    country: "BA",
    latitude: 43.2849,
    longitude: 17.8477,
    frequencies: ["127.6"],
    region: "Bosnia",
    isActive: true,
  },
  {
    icao: "LQBK",
    iata: "BNX",
    name: "Banja Luka Airport",
    city: "Banja Luka",
    country: "BA",
    latitude: 44.9061,
    longitude: 17.2458,
    frequencies: ["127.6"],
    region: "Bosnia",
    isActive: true,
  },
  {
    icao: "LQTZ",
    iata: "TZL",
    name: "Tuzla Airport",
    city: "Tuzla",
    country: "BA",
    latitude: 44.4544,
    longitude: 18.7187,
    frequencies: ["127.6"],
    region: "Bosnia",
    isActive: true,
  },
  // Serbia
  {
    icao: "LYBE",
    iata: "BEG",
    name: "Belgrade Nikola Tesla Airport",
    city: "Belgrade",
    country: "RS",
    latitude: 44.8184,
    longitude: 20.3091,
    frequencies: ["127.6"],
    region: "Serbia",
    isActive: true,
  },
  {
    icao: "LYNI",
    iata: "INI",
    name: "Nis Constantine Airport",
    city: "Nis",
    country: "RS",
    latitude: 43.3386,
    longitude: 21.9523,
    frequencies: ["127.6"],
    region: "Serbia",
    isActive: true,
  },
  // Slovenia
  {
    icao: "LJLJ",
    iata: "LJU",
    name: "Ljubljana Joze Pucnik Airport",
    city: "Ljubljana",
    country: "SI",
    latitude: 46.2237,
    longitude: 14.4576,
    frequencies: ["127.6"],
    region: "Slovenia",
    isActive: true,
  },
  // Slovakia
  {
    icao: "LZIB",
    iata: "BTS",
    name: "Bratislava Airport",
    city: "Bratislava",
    country: "SK",
    latitude: 48.1702,
    longitude: 17.2115,
    frequencies: ["127.6"],
    region: "Slovakia",
    isActive: true,
  },
  // Luxembourg
  {
    icao: "ELLX",
    iata: "LUX",
    name: "Luxembourg Airport",
    city: "Luxembourg",
    country: "LU",
    latitude: 49.6233,
    longitude: 6.2044,
    frequencies: ["127.6"],
    region: "Luxembourg",
    isActive: true,
  },
  // Cyprus
  {
    icao: "LCLK",
    iata: "LCA",
    name: "Larnaca Airport",
    city: "Larnaca",
    country: "CY",
    latitude: 34.8754,
    longitude: 33.6249,
    frequencies: ["127.6"],
    region: "Cyprus",
    isActive: true,
  },
  {
    icao: "LCNC",
    iata: "PFO",
    name: "Paphos Airport",
    city: "Paphos",
    country: "CY",
    latitude: 34.718,
    longitude: 32.4857,
    frequencies: ["127.6"],
    region: "Cyprus",
    isActive: true,
  },
  // Albania
  {
    icao: "LATI",
    iata: "TIA",
    name: "Tirana International Airport",
    city: "Tirana",
    country: "AL",
    latitude: 41.4149,
    longitude: 19.7204,
    frequencies: ["127.6"],
    region: "Albania",
    isActive: true,
  },
  // North Macedonia
  {
    icao: "LWSK",
    iata: "SKP",
    name: "Skopje Airport",
    city: "Skopje",
    country: "MK",
    latitude: 41.9634,
    longitude: 21.6392,
    frequencies: ["127.6"],
    region: "North Macedonia",
    isActive: true,
  },
  {
    icao: "LWOH",
    iata: "OHI",
    name: "Ohrid Airport",
    city: "Ohrid",
    country: "MK",
    latitude: 41.1793,
    longitude: 20.7528,
    frequencies: ["127.6"],
    region: "North Macedonia",
    isActive: true,
  },
  // Montenegro
  {
    icao: "LYTV",
    iata: "TGD",
    name: "Podgorica Airport",
    city: "Podgorica",
    country: "ME",
    latitude: 42.3592,
    longitude: 19.2517,
    frequencies: ["127.6"],
    region: "Montenegro",
    isActive: true,
  },
  {
    icao: "LYPG",
    iata: "TIV",
    name: "Tivat Airport",
    city: "Tivat",
    country: "ME",
    latitude: 42.4032,
    longitude: 18.7518,
    frequencies: ["127.6"],
    region: "Montenegro",
    isActive: true,
  },
  // Gibraltar
  {
    icao: "LXGB",
    iata: "GIB",
    name: "Gibraltar Airport",
    city: "Gibraltar",
    country: "GI",
    latitude: 36.1506,
    longitude: -5.3497,
    frequencies: ["126.2"],
    region: "Gibraltar",
    isActive: true,
  },
  // Turkey
  {
    icao: "LTBA",
    iata: "ISL",
    name: "Istanbul Ataturk Airport",
    city: "Istanbul",
    country: "TR",
    latitude: 40.9738,
    longitude: 28.8145,
    frequencies: ["127.6"],
    region: "Turkey",
    isActive: true,
  },
  {
    icao: "LTFJ",
    iata: "SAW",
    name: "Istanbul Sabiha Gokcen Airport",
    city: "Istanbul",
    country: "TR",
    latitude: 40.8986,
    longitude: 29.3092,
    frequencies: ["127.6"],
    region: "Turkey",
    isActive: true,
  },
  {
    icao: "LTAC",
    iata: "ESB",
    name: "Ankara Esenboga Airport",
    city: "Ankara",
    country: "TR",
    latitude: 40.1281,
    longitude: 32.9951,
    frequencies: ["127.6"],
    region: "Turkey",
    isActive: true,
  },
  {
    icao: "LTAF",
    iata: "AYT",
    name: "Antalya Airport",
    city: "Antalya",
    country: "TR",
    latitude: 36.8987,
    longitude: 30.8005,
    frequencies: ["127.6"],
    region: "Turkey",
    isActive: true,
  },
  {
    icao: "LTAI",
    iata: "ADB",
    name: "Izmir Adnan Menderes Airport",
    city: "Izmir",
    country: "TR",
    latitude: 38.2924,
    longitude: 27.157,
    frequencies: ["127.6"],
    region: "Turkey",
    isActive: true,
  },
  {
    icao: "LTBS",
    iata: "BJV",
    name: "Bodrum Milas Airport",
    city: "Bodrum",
    country: "TR",
    latitude: 37.2506,
    longitude: 27.6643,
    frequencies: ["127.6"],
    region: "Turkey",
    isActive: true,
  },
  {
    icao: "LTCO",
    iata: "DLM",
    name: "Dalaman Airport",
    city: "Dalaman",
    country: "TR",
    latitude: 36.7131,
    longitude: 28.7925,
    frequencies: ["127.6"],
    region: "Turkey",
    isActive: true,
  },
  // Jordan
  {
    icao: "OJAI",
    iata: "AMM",
    name: "Amman Queen Alia Airport",
    city: "Amman",
    country: "JO",
    latitude: 31.7226,
    longitude: 35.9932,
    frequencies: ["127.6"],
    region: "Jordan",
    isActive: true,
  },
  // Israel
  {
    icao: "LLBG",
    iata: "TLV",
    name: "Tel Aviv Ben Gurion Airport",
    city: "Tel Aviv",
    country: "IL",
    latitude: 32.0055,
    longitude: 34.8854,
    frequencies: ["127.6"],
    region: "Israel",
    isActive: true,
  },
  {
    icao: "LLOV",
    iata: "VDA",
    name: "Ovda Airport",
    city: "Ovda",
    country: "IL",
    latitude: 29.9394,
    longitude: 34.9294,
    frequencies: ["127.6"],
    region: "Israel",
    isActive: true,
  },
  {
    icao: "LLIB",
    iata: "ETM",
    name: "Ramon Airport",
    city: "Eilat",
    country: "IL",
    latitude: 29.8335,
    longitude: 35.0064,
    frequencies: ["127.6"],
    region: "Israel",
    isActive: true,
  },
  // Lebanon
  {
    icao: "OLBA",
    iata: "BEY",
    name: "Beirut Rafic Hariri Airport",
    city: "Beirut",
    country: "LB",
    latitude: 33.8209,
    longitude: 35.4884,
    frequencies: ["127.6"],
    region: "Lebanon",
    isActive: true,
  },
];
